plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.itam'
version = '0.0.1-SNAPSHOT'
description = 'discovery-interface'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-restclient'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation files('libs/d42-jdbc-driver-1.0.2-jar-with-dependencies.jar')
    runtimeOnly 'com.ibm.db2:jcc'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
    systemProperty 'jdk.net.hosts.file', file('config/device42-test-hosts').absolutePath
}
