-- OS·Disk·Filesystem·IP에 쓸 ACTCI 분류 후보와 그 스펙을 찾는다.
-- 후보 키워드는 candidate-classifications 블록의 LIKE 목록으로 바꾼다.
-- 후보가 안 나오면 all-actci-classifications 결과를 직접 훑는다.
-- name: classstructure-columns
SELECT TABNAME,COLNAME,TYPENAME,LENGTH,NULLS,COLNO
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('CLASSSTRUCTURE','RELATION','RELATIONRULES')
ORDER BY TABNAME,COLNO;

-- name: all-actci-classifications
SELECT s.CLASSIFICATIONID, s.CLASSSTRUCTUREID
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH cu
        WHERE cu.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID AND cu.OBJECTNAME = 'ACTCI')
ORDER BY s.CLASSIFICATIONID;

-- name: candidate-classifications
SELECT s.CLASSIFICATIONID, s.CLASSSTRUCTUREID,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPECUSEWITH u
       WHERE u.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID AND u.OBJECTNAME = 'ACTCI' AND u.USEINSPEC = 1) AS ACTCI_SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH cu
        WHERE cu.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID AND cu.OBJECTNAME = 'ACTCI')
  AND (s.CLASSIFICATIONID LIKE '%OPERATINGSYSTEM%' OR s.CLASSIFICATIONID LIKE '%OSINSTALL%'
    OR s.CLASSIFICATIONID LIKE '%FILESYSTEM%' OR s.CLASSIFICATIONID LIKE '%DISK%'
    OR s.CLASSIFICATIONID LIKE '%STORAGE%' OR s.CLASSIFICATIONID LIKE '%VOLUME%'
    OR s.CLASSIFICATIONID LIKE '%IPADDR%' OR s.CLASSIFICATIONID LIKE '%IPINTERFACE%'
    OR s.CLASSIFICATIONID LIKE '%NETWORK%' OR s.CLASSIFICATIONID LIKE '%PARTITION%'
    OR s.CLASSIFICATIONID LIKE '%DRIVE%' OR s.CLASSIFICATIONID LIKE '%MEDIA%')
ORDER BY s.CLASSIFICATIONID;

-- name: attribute-name-search
SELECT a.ASSETATTRIBUTEID, a.ASSETATTRID, a.DATATYPE, a.MEASUREUNITID, a.ORGID, a.SITEID
FROM MAXIMO.ASSETATTRIBUTE a
WHERE a.ASSETATTRID LIKE 'OPERATINGSYSTEM%' OR a.ASSETATTRID LIKE 'FILESYSTEM%'
   OR a.ASSETATTRID LIKE 'DISK%' OR a.ASSETATTRID LIKE 'IPADDRESS%'
   OR a.ASSETATTRID LIKE 'IPINTERFACE%' OR a.ASSETATTRID LIKE 'STORAGE%'
   OR a.ASSETATTRID LIKE '%FILESYSTEM%' OR a.ASSETATTRID LIKE '%IPADDR%'
ORDER BY a.ASSETATTRID;

-- name: candidate-specs
SELECT s.CLASSIFICATIONID, c.CLASSSTRUCTUREID, c.CLASSSPECID, c.ASSETATTRID, c.SECTION,
    a.DATATYPE, c.MEASUREUNITID, u.SEQUENCE, u.MANDATORY, u.USEINSPEC, c.ORGID, c.SITEID
FROM MAXIMO.CLASSSTRUCTURE s
JOIN MAXIMO.CLASSSPEC c ON c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE a
  ON a.ASSETATTRIBUTEID = c.ASSETATTRIBUTEID AND a.ASSETATTRID = c.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH u
  ON u.CLASSSPECID = c.CLASSSPECID AND u.OBJECTNAME = 'ACTCI'
WHERE s.CLASSIFICATIONID IN (
    'SYS.OPERATINGSYSTEM', 'SYS.WINDOWS.WINDOWSOPERATINGSYSTEM',
    'SYS.FILESYSTEM', 'SYS.LOCALFILESYSTEM', 'SYS.UNIX.UNIXFILESYSTEM', 'SYS.WINDOWS.WINDOWSFILESYSTEM',
    'NET.IPADDRESS', 'NET.IPINTERFACE',
    'DEV.DISKDRIVE', 'DEV.DISKPARTITION', 'DEV.STORAGEVOLUME')
ORDER BY s.CLASSIFICATIONID, c.ASSETATTRID;

-- name: relation-rules-computer-to-component
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS, ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.RELATIONNUM, r.CONTAINMENT, r.CARDINALITY, r.REVRELATIONSHIP, r.SWAPPED, r.PROPAGATECHANGE
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
  AND ts.CLASSIFICATIONID IN ('SYS.OPERATINGSYSTEM','SYS.FILESYSTEM','NET.IPADDRESS','DEV.DISKDRIVE')
ORDER BY 1,2,3;

-- name: relation-rules-component-to-computer
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS, ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.RELATIONNUM, r.CONTAINMENT, r.CARDINALITY, r.REVRELATIONSHIP, r.SWAPPED, r.PROPAGATECHANGE
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN ('SYS.OPERATINGSYSTEM','SYS.FILESYSTEM','NET.IPADDRESS','DEV.DISKDRIVE')
  AND ts.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
ORDER BY 1,2,3;

-- name: relation-definitions-used
SELECT d.RELATIONNUM, d.DESCRIPTION, d.USEWITH, d.TYPE, d.COMPRELATION, d.CLASSSTRUCTUREID
FROM MAXIMO.RELATION d
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.RELATIONRULES r
    JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
    JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
    WHERE r.RELATIONNUM = d.RELATIONNUM
      AND ss.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM',
          'SYS.OPERATINGSYSTEM','SYS.FILESYSTEM','NET.IPADDRESS','DEV.DISKDRIVE')
      AND ts.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM',
          'SYS.OPERATINGSYSTEM','SYS.FILESYSTEM','NET.IPADDRESS','DEV.DISKDRIVE'))
ORDER BY d.RELATIONNUM;

-- name: ipaddress-any-relation
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS, ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.RELATIONNUM, r.CONTAINMENT, r.CARDINALITY
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID = 'NET.IPADDRESS' OR ts.CLASSIFICATIONID = 'NET.IPADDRESS'
ORDER BY 1,2,3;

-- name: ipinterface-computer-relation
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS, ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.RELATIONNUM, r.CONTAINMENT, r.CARDINALITY
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE (ss.CLASSIFICATIONID = 'NET.IPINTERFACE' AND ts.CLASSIFICATIONID LIKE 'SYS.%COMPUTERSYSTEM')
   OR (ts.CLASSIFICATIONID = 'NET.IPINTERFACE' AND ss.CLASSIFICATIONID LIKE 'SYS.%COMPUTERSYSTEM')
   OR (ss.CLASSIFICATIONID = 'NET.IPINTERFACE' AND ts.CLASSIFICATIONID = 'NET.IPADDRESS')
   OR (ss.CLASSIFICATIONID = 'NET.IPADDRESS' AND ts.CLASSIFICATIONID = 'NET.IPINTERFACE')
ORDER BY 1,2,3;

-- name: computer-outgoing-relation-targets
SELECT ts.CLASSIFICATIONID AS TARGET_CLASS, r.RELATIONNUM, r.CARDINALITY, COUNT(*) AS RULE_COUNT
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID = 'SYS.COMPUTERSYSTEM'
  AND (ts.CLASSIFICATIONID LIKE 'NET.%' OR ts.CLASSIFICATIONID LIKE '%IPADDR%')
GROUP BY ts.CLASSIFICATIONID, r.RELATIONNUM, r.CARDINALITY
ORDER BY 1,2;
