-- CI 분류 계층과 대표 템플릿의 적용 설정을 검증한다.
-- 분류 대상은 CLASSIFICATIONID 목록으로 선택한다. PK 리터럴은 사용하지 않는다.

-- name: ci-class-hierarchy
SELECT U.OBJECTNAME,COUNT(*) AS ROW_CNT,
SUM(CASE WHEN S.PARENT IS NULL THEN 1 ELSE 0 END) AS ROOT_ROWS,
SUM(CASE WHEN S.PARENT IS NOT NULL AND EXISTS (SELECT 1 FROM MAXIMO.CLASSSTRUCTURE P WHERE P.CLASSSTRUCTUREID=S.PARENT) THEN 1 ELSE 0 END) AS PARENT_MATCH,
SUM(CASE WHEN S.PARENT IS NOT NULL AND NOT EXISTS (SELECT 1 FROM MAXIMO.CLASSSTRUCTURE P WHERE P.CLASSSTRUCTUREID=S.PARENT) THEN 1 ELSE 0 END) AS PARENT_MISSING,
SUM(CASE WHEN S.PARENT=S.CLASSSTRUCTUREID THEN 1 ELSE 0 END) AS SELF_PARENT,
COUNT(S.ORGID) AS ORG_ROWS,COUNT(S.SITEID) AS SITE_ROWS
FROM MAXIMO.CLASSUSEWITH U JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=U.CLASSSTRUCTUREID
WHERE U.OBJECTNAME IN ('ACTCI','CI') GROUP BY U.OBJECTNAME;

-- name: ci-class-template-samples
SELECT S.CLASSIFICATIONID,S.CLASSSTRUCTUREID,U.OBJECTNAME,
C.ASSETATTRID,A.DESCRIPTION,A.DATATYPE,C.SECTION,C.MEASUREUNITID,C.DOMAINID,
C.INHERITEDFROMID,C.APPLYDOWNHIER,U.MANDATORY,U.SEQUENCE,U.USEINSPEC,U.USEINDESC,
U.DEFAULTALNVALUE,U.DEFAULTNUMVALUE,U.DEFAULTTABLEVALUE
FROM MAXIMO.CLASSSTRUCTURE S
JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID
JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID
WHERE U.OBJECTNAME IN ('ACTCI','CI') AND S.CLASSIFICATIONID IN
('APP.DB.DATABASE','APP.DB.DATABASESERVER','SYS.COMPUTERSYSTEM','SERVICE.SERVICEINSTANCE','GENCSYS','OS')
ORDER BY S.CLASSIFICATIONID,U.SEQUENCE,C.ASSETATTRID;

-- name: ci-class-missing-parents
SELECT U.OBJECTNAME,S.CLASSSTRUCTUREID,S.CLASSIFICATIONID,S.PARENT
FROM MAXIMO.CLASSUSEWITH U JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=U.CLASSSTRUCTUREID
WHERE U.OBJECTNAME IN ('ACTCI','CI') AND S.PARENT IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM MAXIMO.CLASSSTRUCTURE P WHERE P.CLASSSTRUCTUREID=S.PARENT)
ORDER BY U.OBJECTNAME,S.CLASSIFICATIONID;

-- name: ci-class-lookup-quality
SELECT U.OBJECTNAME,COUNT(*) AS ROW_CNT,
SUM(CASE WHEN U.OBJECTVALUE IS NOT NULL THEN 1 ELSE 0 END) AS OBJECTVALUE_ROWS,
SUM(CASE WHEN U.TOPLEVEL=1 THEN 1 ELSE 0 END) AS TOPLEVEL_ROWS,
SUM(CASE WHEN U.AUTOCREATECI=1 THEN 1 ELSE 0 END) AS AUTOCREATECI_ROWS
FROM MAXIMO.CLASSUSEWITH U WHERE U.OBJECTNAME IN ('ACTCI','CI') GROUP BY U.OBJECTNAME;

-- name: ci-classspec-use-flags
SELECT OBJECTNAME,USEINSPEC,USEINDESC,MANDATORY,COUNT(*) AS ROW_CNT
FROM MAXIMO.CLASSSPECUSEWITH WHERE OBJECTNAME IN ('ACTCI','CI')
GROUP BY OBJECTNAME,USEINSPEC,USEINDESC,MANDATORY
ORDER BY OBJECTNAME,USEINSPEC,USEINDESC;

-- name: ci-relation-definitions
SELECT USEWITH,TYPE,COUNT(*) AS ROW_CNT,COUNT(COMPRELATION) AS COMPLEMENT_ROWS,COUNT(CLASSSTRUCTUREID) AS CLASS_ROWS
FROM MAXIMO.RELATION GROUP BY USEWITH,TYPE ORDER BY USEWITH,TYPE;

-- name: ci-relation-candidates
SELECT RELATIONNUM,DESCRIPTION,TYPE,COMPRELATION,USEWITH,CLASSSTRUCTUREID,IMPACTON
FROM MAXIMO.RELATION
WHERE UPPER(RELATIONNUM) LIKE '%RUNSON%' OR UPPER(RELATIONNUM) LIKE '%CONTAINS%'
   OR UPPER(RELATIONNUM) LIKE '%HOST%' OR UPPER(RELATIONNUM) LIKE '%INSTAL%'
ORDER BY RELATIONNUM;

-- name: ci-classification-discovery
SELECT S.CLASSIFICATIONID,S.CLASSSTRUCTUREID,S.PARENT,U.OBJECTNAME
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSUSEWITH U ON U.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
WHERE U.OBJECTNAME IN ('ACTCI','CI')
AND (UPPER(S.CLASSIFICATIONID) LIKE '%KUBERNET%' OR UPPER(S.DESCRIPTION) LIKE '%KUBERNET%'
OR UPPER(S.CLASSIFICATIONID) LIKE '%K8S%' OR UPPER(S.DESCRIPTION) LIKE '%K8S%')
ORDER BY S.CLASSIFICATIONID;
