-- Actual CI의 빈 테이블은 메타데이터로, CI의 사용 패턴은 집계로 확인한다.
-- 분류 후보 검색은 class-candidates 블록의 LIKE 목록에서 확장한다.

-- name: ci-reference-coverage
SELECT COUNT(*) AS ROW_CNT,COUNT(ACTCINUM) AS ACTCINUM_ROWS,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSSTRUCTURE S WHERE S.CLASSSTRUCTUREID=C.CLASSSTRUCTUREID) THEN 1 ELSE 0 END) AS CLASS_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH U WHERE U.CLASSSTRUCTUREID=C.CLASSSTRUCTUREID AND U.OBJECTNAME='CI') THEN 1 ELSE 0 END) AS CI_USEWITH_MATCH
FROM MAXIMO.CI C;

-- name: ci-reference-types
SELECT S.CLASSIFICATIONID,C.STATUS,C.LANGCODE,COUNT(*) AS ROW_CNT
FROM MAXIMO.CI C LEFT JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=C.CLASSSTRUCTUREID
GROUP BY S.CLASSIFICATIONID,C.STATUS,C.LANGCODE ORDER BY S.CLASSIFICATIONID,C.STATUS;

-- name: cispec-reference-coverage
SELECT COUNT(*) AS ROW_CNT,COUNT(REFOBJECTID) AS REFID_ROWS,COUNT(CLASSSPECID) AS CLASSSPECID_ROWS,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CI C WHERE C.CIID=S.REFOBJECTID AND C.CINUM=S.CINUM) THEN 1 ELSE 0 END) AS PARENT_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CI C WHERE C.CINUM=S.CINUM AND C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID) THEN 1 ELSE 0 END) AS PARENT_CLASS_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSSPEC T WHERE T.CLASSSPECID=S.CLASSSPECID AND T.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID AND T.ASSETATTRID=S.ASSETATTRID AND (T.SECTION=S.SECTION OR (T.SECTION IS NULL AND S.SECTION IS NULL))) THEN 1 ELSE 0 END) AS TEMPLATE_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.ASSETATTRIBUTE A WHERE A.ASSETATTRIBUTEID=S.ASSETATTRIBUTEID AND A.ASSETATTRID=S.ASSETATTRID) THEN 1 ELSE 0 END) AS ATTRIBUTE_MATCH,
COUNT(ALNVALUE) AS ALN_ROWS,COUNT(NUMVALUE) AS NUM_ROWS,COUNT(TABLEVALUE) AS TABLE_ROWS,COUNT(DATEVALUE) AS DATE_ROWS
FROM MAXIMO.CISPEC S;

-- name: cispec-reference-template
SELECT S.REFOBJECTNAME,S.MANDATORY,S.DISPLAYSEQUENCE,A.DATATYPE,
COUNT(*) AS ROW_CNT,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSSPECUSEWITH U WHERE U.CLASSSPECID=S.CLASSSPECID AND U.OBJECTNAME='CI' AND U.MANDATORY=S.MANDATORY AND U.SEQUENCE=S.DISPLAYSEQUENCE) THEN 1 ELSE 0 END) AS USEWITH_MATCH
FROM MAXIMO.CISPEC S LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRIBUTEID=S.ASSETATTRIBUTEID
GROUP BY S.REFOBJECTNAME,S.MANDATORY,S.DISPLAYSEQUENCE,A.DATATYPE
ORDER BY S.REFOBJECTNAME,A.DATATYPE,S.DISPLAYSEQUENCE;

-- name: cirelation-reference
SELECT C.RELATIONNUM,R.TYPE,R.COMPRELATION,R.USEWITH,COUNT(*) AS ROW_CNT,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CI S WHERE S.CINUM=C.SOURCECI) THEN 1 ELSE 0 END) AS SOURCE_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CI T WHERE T.CINUM=C.TARGETCI) THEN 1 ELSE 0 END) AS TARGET_MATCH,
COUNT(C.PARENTCI) AS PARENT_ROWS,COUNT(C.ANCESTORCI) AS ANCESTOR_ROWS
FROM MAXIMO.CIRELATION C LEFT JOIN MAXIMO.RELATION R ON R.RELATIONNUM=C.RELATIONNUM
GROUP BY C.RELATIONNUM,R.TYPE,R.COMPRELATION,R.USEWITH ORDER BY C.RELATIONNUM;

-- name: class-usewith-counts
SELECT U.OBJECTNAME,COUNT(*) AS ROW_CNT,COUNT(DISTINCT U.CLASSSTRUCTUREID) AS CLASSES
FROM MAXIMO.CLASSUSEWITH U WHERE U.OBJECTNAME IN ('ACTCI','CI')
GROUP BY U.OBJECTNAME;

-- name: class-usewith-families
SELECT U.OBJECTNAME,
CASE WHEN S.CLASSIFICATIONID LIKE 'ACTCI.%' THEN 'ACTCI'
     WHEN S.CLASSIFICATIONID LIKE 'CI.%' THEN 'CI'
     WHEN S.CLASSIFICATIONID LIKE 'SCI.%' THEN 'SCI' ELSE 'OTHER' END AS FAMILY,
COUNT(*) AS ROW_CNT
FROM MAXIMO.CLASSUSEWITH U JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=U.CLASSSTRUCTUREID
WHERE U.OBJECTNAME IN ('ACTCI','CI')
GROUP BY U.OBJECTNAME,CASE WHEN S.CLASSIFICATIONID LIKE 'ACTCI.%' THEN 'ACTCI' WHEN S.CLASSIFICATIONID LIKE 'CI.%' THEN 'CI' WHEN S.CLASSIFICATIONID LIKE 'SCI.%' THEN 'SCI' ELSE 'OTHER' END
ORDER BY U.OBJECTNAME,FAMILY;

-- name: class-usewith-overlap
SELECT COUNT(*) AS ACTCI_CLASSES,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH C WHERE C.CLASSSTRUCTUREID=A.CLASSSTRUCTUREID AND C.OBJECTNAME='CI') THEN 1 ELSE 0 END) AS ALSO_CI
FROM MAXIMO.CLASSUSEWITH A WHERE A.OBJECTNAME='ACTCI';

-- name: class-candidates
SELECT S.CLASSSTRUCTUREID,S.CLASSIFICATIONID,S.PARENT,S.DESCRIPTION,S.ORGID,S.SITEID,U.OBJECTNAME,
(SELECT COUNT(*) FROM MAXIMO.CLASSSPEC C WHERE C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID) AS SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSUSEWITH U ON U.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
WHERE U.OBJECTNAME IN ('ACTCI','CI') AND
(UPPER(S.CLASSIFICATIONID) LIKE '%DATABASE%' OR UPPER(S.CLASSIFICATIONID) LIKE '%COMPUTERSYSTEM%'
 OR UPPER(S.CLASSIFICATIONID) LIKE '%INSTANCE%' OR UPPER(S.CLASSIFICATIONID) LIKE '%KUBERNET%'
 OR UPPER(S.CLASSIFICATIONID) LIKE '%K8S%' OR UPPER(S.CLASSIFICATIONID) LIKE '%BUSINESSSERVICE%'
 OR UPPER(S.CLASSIFICATIONID) LIKE '%WEBSERVER%')
ORDER BY U.OBJECTNAME,S.CLASSIFICATIONID,S.CLASSSTRUCTUREID;

-- name: classspec-usewith-counts
SELECT U.OBJECTNAME,COUNT(*) AS ROW_CNT,COUNT(DISTINCT U.CLASSSPECID) AS SPECS,
SUM(CASE WHEN U.MANDATORY=1 THEN 1 ELSE 0 END) AS MANDATORY_ROWS,
COUNT(U.DEFAULTALNVALUE) AS ALN_DEFAULTS,COUNT(U.DEFAULTNUMVALUE) AS NUM_DEFAULTS,
COUNT(U.DEFAULTTABLEVALUE) AS TABLE_DEFAULTS
FROM MAXIMO.CLASSSPECUSEWITH U WHERE U.OBJECTNAME IN ('ACTCI','CI')
GROUP BY U.OBJECTNAME;

-- name: classspec-integrity
SELECT U.OBJECTNAME,COUNT(*) AS ROW_CNT,
SUM(CASE WHEN C.CLASSSPECID IS NOT NULL THEN 1 ELSE 0 END) AS TEMPLATE_MATCH,
SUM(CASE WHEN C.CLASSSTRUCTUREID=U.CLASSSTRUCTUREID AND C.ASSETATTRID=U.ASSETATTRID AND (C.SECTION=U.SECTION OR (C.SECTION IS NULL AND U.SECTION IS NULL)) THEN 1 ELSE 0 END) AS FIELDS_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH W WHERE W.CLASSSTRUCTUREID=C.CLASSSTRUCTUREID AND W.OBJECTNAME=U.OBJECTNAME) THEN 1 ELSE 0 END) AS CLASS_USEWITH_MATCH,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.ASSETATTRIBUTE A WHERE A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID AND A.ASSETATTRID=C.ASSETATTRID) THEN 1 ELSE 0 END) AS ATTRIBUTE_MATCH,
SUM(CASE WHEN C.INHERITEDFROMID IS NOT NULL THEN 1 ELSE 0 END) AS INHERITED_ROWS,
SUM(CASE WHEN C.APPLYDOWNHIER=1 THEN 1 ELSE 0 END) AS APPLYDOWN_ROWS
FROM MAXIMO.CLASSSPECUSEWITH U LEFT JOIN MAXIMO.CLASSSPEC C ON C.CLASSSPECID=U.CLASSSPECID
WHERE U.OBJECTNAME IN ('ACTCI','CI') GROUP BY U.OBJECTNAME;

-- name: classspec-datatypes
SELECT U.OBJECTNAME,A.DATATYPE,COUNT(*) AS ROW_CNT,COUNT(C.DOMAINID) AS SPEC_DOMAINS,COUNT(A.DOMAINID) AS ATTRIBUTE_DOMAINS
FROM MAXIMO.CLASSSPECUSEWITH U JOIN MAXIMO.CLASSSPEC C ON C.CLASSSPECID=U.CLASSSPECID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID
WHERE U.OBJECTNAME IN ('ACTCI','CI')
GROUP BY U.OBJECTNAME,A.DATATYPE ORDER BY U.OBJECTNAME,A.DATATYPE;

-- name: ci-status-domain
SELECT DOMAINID,VALUE,MAXVALUE,DEFAULTS,DESCRIPTION
FROM MAXIMO.SYNONYMDOMAIN WHERE DOMAINID='CISTATUS' ORDER BY VALUE;

-- name: ci-maxsequence
SELECT TBNAME,NAME,MAXRESERVED,MAXVALUE,RANGE,SEQUENCENAME
FROM MAXIMO.MAXSEQUENCE WHERE TBNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSTRUCTURE','CLASSSPEC')
ORDER BY TBNAME,NAME;

-- name: ci-constraints
SELECT TABNAME,CONSTNAME,TYPE FROM SYSCAT.TABCONST
WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSTRUCTURE','CLASSSPEC')
ORDER BY TABNAME,CONSTNAME;

-- name: ci-triggers
SELECT TABNAME,TRIGNAME,TRIGTIME,TRIGEVENT,CAST(TEXT AS VARCHAR(8000)) AS DEFINITION
FROM SYSCAT.TRIGGERS WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION')
ORDER BY TABNAME,TRIGNAME;

