-- CLASSSPEC 적용 범위는 CLASSUSEWITH 기준. EXISTS로 중복 행을 방지한다.
-- name: cache-counts
SELECT 'CLASSSPEC_ALL' AS SCOPE, COUNT_BIG(*) AS ROW_COUNT FROM MAXIMO.CLASSSPEC
UNION ALL
SELECT 'CLASSSPEC_ACTCI', COUNT_BIG(*) FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI')
UNION ALL
SELECT 'CLASSSPEC_ACTCI_CI', COUNT_BIG(*) FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME IN ('ACTCI','CI'))
UNION ALL
SELECT 'ASSETATTRIBUTE_ALL', COUNT_BIG(*) FROM MAXIMO.ASSETATTRIBUTE;

-- name: columns
SELECT TABNAME,COLNAME,TYPENAME,LENGTH,SCALE,NULLS,COLNO
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('CLASSSPEC','ASSETATTRIBUTE')
ORDER BY TABNAME,COLNO;

-- name: classspec-all
SELECT c.* FROM MAXIMO.CLASSSPEC c ORDER BY c.CLASSSPECID;

-- name: classspec-actci
SELECT c.* FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI')
ORDER BY c.CLASSSPECID;

-- name: classspec-actci-ci
SELECT c.* FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME IN ('ACTCI','CI'))
ORDER BY c.CLASSSPECID;

-- name: assetattribute-all
SELECT a.* FROM MAXIMO.ASSETATTRIBUTE a ORDER BY a.ASSETATTRIBUTEID;

-- name: usage-counts
SELECT OBJECTNAME,COUNT_BIG(*) AS ROW_COUNT FROM MAXIMO.CLASSSPECUSEWITH
WHERE OBJECTNAME IN ('ACTCI','CI') GROUP BY OBJECTNAME;

-- name: duplicate-attribute-names
SELECT COUNT(*) AS DUPLICATE_NAMES FROM (
  SELECT ASSETATTRID FROM MAXIMO.ASSETATTRIBUTE GROUP BY ASSETATTRID HAVING COUNT(*)>1
) d;
