-- 컬럼 값의 바이트 합. NULL/행 헤더/가변길이 헤더/인덱스/압축/빈 페이지는 제외.

-- name: payload-classspec-all
SELECT COUNT_BIG(*) AS ROW_COUNT,
       SUM(BIGINT(COALESCE(OCTET_LENGTH(c.CLASSSTRUCTUREID),0) +
       COALESCE(OCTET_LENGTH(c.ASSETATTRID),0) +
       COALESCE(OCTET_LENGTH(c.MEASUREUNITID),0) +
       COALESCE(OCTET_LENGTH(c.DOMAINID),0) +
       COALESCE(OCTET_LENGTH(c.ATTRDESCPREFIX),0) +
       COALESCE(OCTET_LENGTH(c.CS01),0) +
       COALESCE(OCTET_LENGTH(c.CS02),0) +
       COALESCE(OCTET_LENGTH(c.CS03),0) +
       COALESCE(LENGTH(c.CS04),0) +
       COALESCE(LENGTH(c.CS05),0) +
       COALESCE(OCTET_LENGTH(c.ORGID),0) +
       COALESCE(OCTET_LENGTH(c.SECTION),0) +
       COALESCE(OCTET_LENGTH(c.SITEID),0) +
       COALESCE(LENGTH(c.CLASSSPECID),0) +
       COALESCE(LENGTH(c.APPLYDOWNHIER),0) +
       COALESCE(OCTET_LENGTH(c.INHERITEDFROM),0) +
       COALESCE(LENGTH(c.INHERITEDFROMID),0) +
       COALESCE(OCTET_LENGTH(c.TABLEATTRIBUTE),0) +
       COALESCE(OCTET_LENGTH(c.LOOKUPNAME),0) +
       COALESCE(OCTET_LENGTH(c.LINKEDTOATTRIBUTE),0) +
       COALESCE(OCTET_LENGTH(c.LINKEDTOSECTION),0) +
       COALESCE(LENGTH(c.ASSETATTRIBUTEID),0) +
       COALESCE(LENGTH(c.CONTINUOUS),0) +
       COALESCE(OCTET_LENGTH(c.LINEARTYPE),0) +
       COALESCE(LENGTH(c.ROWSTAMP),0) +
       COALESCE(LENGTH(c.PLUSPISGLOBAL),0) +
       COALESCE(OCTET_LENGTH(c.PLUSPINSERTCUSTOMER),0))) AS VALUE_BYTES
FROM MAXIMO.CLASSSPEC c
;

-- name: payload-classspec-actci
SELECT COUNT_BIG(*) AS ROW_COUNT,
       SUM(BIGINT(COALESCE(OCTET_LENGTH(c.CLASSSTRUCTUREID),0) +
       COALESCE(OCTET_LENGTH(c.ASSETATTRID),0) +
       COALESCE(OCTET_LENGTH(c.MEASUREUNITID),0) +
       COALESCE(OCTET_LENGTH(c.DOMAINID),0) +
       COALESCE(OCTET_LENGTH(c.ATTRDESCPREFIX),0) +
       COALESCE(OCTET_LENGTH(c.CS01),0) +
       COALESCE(OCTET_LENGTH(c.CS02),0) +
       COALESCE(OCTET_LENGTH(c.CS03),0) +
       COALESCE(LENGTH(c.CS04),0) +
       COALESCE(LENGTH(c.CS05),0) +
       COALESCE(OCTET_LENGTH(c.ORGID),0) +
       COALESCE(OCTET_LENGTH(c.SECTION),0) +
       COALESCE(OCTET_LENGTH(c.SITEID),0) +
       COALESCE(LENGTH(c.CLASSSPECID),0) +
       COALESCE(LENGTH(c.APPLYDOWNHIER),0) +
       COALESCE(OCTET_LENGTH(c.INHERITEDFROM),0) +
       COALESCE(LENGTH(c.INHERITEDFROMID),0) +
       COALESCE(OCTET_LENGTH(c.TABLEATTRIBUTE),0) +
       COALESCE(OCTET_LENGTH(c.LOOKUPNAME),0) +
       COALESCE(OCTET_LENGTH(c.LINKEDTOATTRIBUTE),0) +
       COALESCE(OCTET_LENGTH(c.LINKEDTOSECTION),0) +
       COALESCE(LENGTH(c.ASSETATTRIBUTEID),0) +
       COALESCE(LENGTH(c.CONTINUOUS),0) +
       COALESCE(OCTET_LENGTH(c.LINEARTYPE),0) +
       COALESCE(LENGTH(c.ROWSTAMP),0) +
       COALESCE(LENGTH(c.PLUSPISGLOBAL),0) +
       COALESCE(OCTET_LENGTH(c.PLUSPINSERTCUSTOMER),0))) AS VALUE_BYTES
FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME IN ('ACTCI'));

-- name: payload-classspec-actci-ci
SELECT COUNT_BIG(*) AS ROW_COUNT,
       SUM(BIGINT(COALESCE(OCTET_LENGTH(c.CLASSSTRUCTUREID),0) +
       COALESCE(OCTET_LENGTH(c.ASSETATTRID),0) +
       COALESCE(OCTET_LENGTH(c.MEASUREUNITID),0) +
       COALESCE(OCTET_LENGTH(c.DOMAINID),0) +
       COALESCE(OCTET_LENGTH(c.ATTRDESCPREFIX),0) +
       COALESCE(OCTET_LENGTH(c.CS01),0) +
       COALESCE(OCTET_LENGTH(c.CS02),0) +
       COALESCE(OCTET_LENGTH(c.CS03),0) +
       COALESCE(LENGTH(c.CS04),0) +
       COALESCE(LENGTH(c.CS05),0) +
       COALESCE(OCTET_LENGTH(c.ORGID),0) +
       COALESCE(OCTET_LENGTH(c.SECTION),0) +
       COALESCE(OCTET_LENGTH(c.SITEID),0) +
       COALESCE(LENGTH(c.CLASSSPECID),0) +
       COALESCE(LENGTH(c.APPLYDOWNHIER),0) +
       COALESCE(OCTET_LENGTH(c.INHERITEDFROM),0) +
       COALESCE(LENGTH(c.INHERITEDFROMID),0) +
       COALESCE(OCTET_LENGTH(c.TABLEATTRIBUTE),0) +
       COALESCE(OCTET_LENGTH(c.LOOKUPNAME),0) +
       COALESCE(OCTET_LENGTH(c.LINKEDTOATTRIBUTE),0) +
       COALESCE(OCTET_LENGTH(c.LINKEDTOSECTION),0) +
       COALESCE(LENGTH(c.ASSETATTRIBUTEID),0) +
       COALESCE(LENGTH(c.CONTINUOUS),0) +
       COALESCE(OCTET_LENGTH(c.LINEARTYPE),0) +
       COALESCE(LENGTH(c.ROWSTAMP),0) +
       COALESCE(LENGTH(c.PLUSPISGLOBAL),0) +
       COALESCE(OCTET_LENGTH(c.PLUSPINSERTCUSTOMER),0))) AS VALUE_BYTES
FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME IN ('ACTCI','CI'));

-- name: payload-assetattribute-all
SELECT COUNT_BIG(*) AS ROW_COUNT,
       SUM(BIGINT(COALESCE(OCTET_LENGTH(c.ASSETATTRID),0) +
       COALESCE(OCTET_LENGTH(c.DESCRIPTION),0) +
       COALESCE(OCTET_LENGTH(c.DATATYPE),0) +
       COALESCE(OCTET_LENGTH(c.MEASUREUNITID),0) +
       COALESCE(OCTET_LENGTH(c.DOMAINID),0) +
       COALESCE(OCTET_LENGTH(c.ATTRDESCPREFIX),0) +
       COALESCE(OCTET_LENGTH(c.ORGID),0) +
       COALESCE(OCTET_LENGTH(c.SITEID),0) +
       COALESCE(LENGTH(c.ASSETATTRIBUTEID),0) +
       COALESCE(LENGTH(c.ROWSTAMP),0))) AS VALUE_BYTES
FROM MAXIMO.ASSETATTRIBUTE c
;

-- name: physical-size
SELECT TABNAME,DATA_OBJECT_P_SIZE,INDEX_OBJECT_P_SIZE,LONG_OBJECT_P_SIZE,LOB_OBJECT_P_SIZE
FROM SYSIBMADM.ADMINTABINFO
WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('CLASSSPEC','ASSETATTRIBUTE');
