-- 일반 DB·DB Server 분류의 속성·관계 설정을 읽기 검증한다.
-- 속성 이름 조인은 누락 진단용이다. 저장된 ASSETATTRIBUTEID의 정상 연결과 구분한다.

-- name: ci-db-target-specs
SELECT S.CLASSIFICATIONID,S.CLASSSTRUCTUREID,C.CLASSSPECID,C.ASSETATTRID,A.DATATYPE,
C.ASSETATTRIBUTEID,CASE WHEN C.ASSETATTRIBUTEID=A.ASSETATTRIBUTEID THEN 1 ELSE 0 END AS ATTRIBUTE_ID_MATCH,
C.SECTION,C.MEASUREUNITID,C.LINKEDTOATTRIBUTE,C.LINKEDTOSECTION,
U.OBJECTNAME,U.MANDATORY,U.SEQUENCE,U.USEINSPEC,U.DEFAULTALNVALUE,U.DEFAULTNUMVALUE,U.DEFAULTTABLEVALUE
FROM MAXIMO.CLASSSTRUCTURE S
JOIN MAXIMO.CLASSUSEWITH W ON W.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID AND W.OBJECTNAME='ACTCI'
JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRID=C.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID AND U.OBJECTNAME='ACTCI'
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','APP.DB.DATABASESERVER')
ORDER BY S.CLASSIFICATIONID,C.ASSETATTRID;

-- name: ci-db-target-containment
SELECT S.CLASSIFICATIONID AS SOURCE_CLASS,T.CLASSIFICATIONID AS TARGET_CLASS,
R.RELATIONNUM,R.CARDINALITY,R.CONTAINMENT,R.REVRELATIONSHIP,R.SWAPPED
FROM MAXIMO.RELATIONRULES R
JOIN MAXIMO.RELATION L ON L.RELATIONNUM=R.RELATIONNUM
JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=R.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE T ON T.CLASSSTRUCTUREID=R.TARGETCLASS
WHERE S.CLASSIFICATIONID='APP.DB.DATABASESERVER' AND T.CLASSIFICATIONID='APP.DB.DATABASE';

-- name: ci-db-relation-definition
SELECT RELATIONNUM,TYPE,USEWITH,COMPRELATION FROM MAXIMO.RELATION
WHERE RELATIONNUM IN ('RELATION.CONTAINS','RELATION.RUNSON') ORDER BY RELATIONNUM;
