-- CI 정의 캐시가 읽는 템플릿의 조직·사이트 범위를 확인한다.
-- 대상 분류는 classspec-orgsite-distribution의 IN 목록으로 바꾼다.
-- name: definition-unique-indexes
SELECT i.TABNAME,i.INDNAME,i.UNIQUERULE,i.COLNAMES
FROM SYSCAT.INDEXES i
WHERE i.TABSCHEMA='MAXIMO' AND i.TABNAME IN ('CLASSSPEC','CLASSSPECUSEWITH','ASSETATTRIBUTE')
ORDER BY i.TABNAME,i.INDNAME;

-- name: classspec-orgsite-distribution
SELECT 'CLASSSPEC_ALL' AS SCOPE,
    CASE WHEN c.ORGID IS NULL THEN 'NULL' ELSE 'SET' END AS ORG_STATE,
    CASE WHEN c.SITEID IS NULL THEN 'NULL' ELSE 'SET' END AS SITE_STATE,
    COUNT_BIG(*) AS ROW_COUNT
FROM MAXIMO.CLASSSPEC c
GROUP BY CASE WHEN c.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
         CASE WHEN c.SITEID IS NULL THEN 'NULL' ELSE 'SET' END
UNION ALL
SELECT 'CLASSSPEC_ACTCI',
    CASE WHEN c.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
    CASE WHEN c.SITEID IS NULL THEN 'NULL' ELSE 'SET' END,
    COUNT_BIG(*)
FROM MAXIMO.CLASSSPEC c
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
  WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI')
GROUP BY CASE WHEN c.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
         CASE WHEN c.SITEID IS NULL THEN 'NULL' ELSE 'SET' END
UNION ALL
SELECT 'CLASSSPEC_SELECTED',
    CASE WHEN c.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
    CASE WHEN c.SITEID IS NULL THEN 'NULL' ELSE 'SET' END,
    COUNT_BIG(*)
FROM MAXIMO.CLASSSPEC c
JOIN MAXIMO.CLASSSTRUCTURE s ON s.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID
WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
GROUP BY CASE WHEN c.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
         CASE WHEN c.SITEID IS NULL THEN 'NULL' ELSE 'SET' END
UNION ALL
SELECT 'CLASSSPECUSEWITH_ACTCI',
    CASE WHEN u.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
    CASE WHEN u.SITEID IS NULL THEN 'NULL' ELSE 'SET' END,
    COUNT_BIG(*)
FROM MAXIMO.CLASSSPECUSEWITH u
WHERE u.OBJECTNAME='ACTCI'
GROUP BY CASE WHEN u.ORGID IS NULL THEN 'NULL' ELSE 'SET' END,
         CASE WHEN u.SITEID IS NULL THEN 'NULL' ELSE 'SET' END
ORDER BY 1,2,3;

-- name: speckey-collisions
SELECT 'ACTCI' AS SCOPE, COUNT_BIG(*) AS COLLIDING_KEYS, COALESCE(MAX(k.ROW_COUNT),0) AS MAX_ROWS_PER_KEY
FROM (
  SELECT c.CLASSSTRUCTUREID, c.ASSETATTRID, c.SECTION, COUNT_BIG(*) AS ROW_COUNT
  FROM MAXIMO.CLASSSPEC c
  WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u
    WHERE u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI')
  GROUP BY c.CLASSSTRUCTUREID, c.ASSETATTRID, c.SECTION
  HAVING COUNT_BIG(*)>1
) k
UNION ALL
SELECT 'SELECTED', COUNT_BIG(*), COALESCE(MAX(k.ROW_COUNT),0)
FROM (
  SELECT c.CLASSSTRUCTUREID, c.ASSETATTRID, c.SECTION, COUNT_BIG(*) AS ROW_COUNT
  FROM MAXIMO.CLASSSPEC c
  JOIN MAXIMO.CLASSSTRUCTURE s ON s.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID
  WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
  GROUP BY c.CLASSSTRUCTUREID, c.ASSETATTRID, c.SECTION
  HAVING COUNT_BIG(*)>1
) k;

-- name: loader-join-fanout
SELECT COUNT_BIG(*) AS JOINED_ROWS, COUNT_BIG(DISTINCT c.CLASSSPECID) AS DISTINCT_CLASSSPEC
FROM MAXIMO.CLASSSPEC c
LEFT JOIN MAXIMO.CLASSSPECUSEWITH u
  ON u.CLASSSPECID=c.CLASSSPECID AND u.OBJECTNAME='ACTCI' AND u.USEINSPEC=1
  AND u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.ASSETATTRID=c.ASSETATTRID
  AND (u.SECTION=c.SECTION OR (u.SECTION IS NULL AND c.SECTION IS NULL))
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH cu
  WHERE cu.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND cu.OBJECTNAME='ACTCI');

-- name: orgscoped-classspec-classes
SELECT s.CLASSIFICATIONID, c.CLASSSTRUCTUREID, c.ORGID, c.SITEID, COUNT_BIG(*) AS ROW_COUNT,
    MAX(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH cu
        WHERE cu.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND cu.OBJECTNAME='ACTCI')
      THEN 'Y' ELSE 'N' END) AS ACTCI_APPLIED
FROM MAXIMO.CLASSSPEC c
JOIN MAXIMO.CLASSSTRUCTURE s ON s.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID
WHERE c.ORGID IS NOT NULL OR c.SITEID IS NOT NULL
GROUP BY s.CLASSIFICATIONID, c.CLASSSTRUCTUREID, c.ORGID, c.SITEID
ORDER BY ROW_COUNT DESC;
