-- 일반 DB·DB Server의 속성명·타입·적용 설정을 조사한다.

-- name: db-spec-inventory
SELECT S.CLASSIFICATIONID,C.ASSETATTRID,A.DESCRIPTION,A.DATATYPE,
C.ASSETATTRIBUTEID,C.SECTION,C.MEASUREUNITID,C.DOMAINID,A.DOMAINID AS ATTRIBUTE_DOMAIN,
U.OBJECTNAME,U.MANDATORY,U.SEQUENCE,U.USEINSPEC
FROM MAXIMO.CLASSSTRUCTURE S
JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRID=C.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID AND U.OBJECTNAME='ACTCI'
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','APP.DB.DATABASESERVER')
ORDER BY S.CLASSIFICATIONID,C.ASSETATTRID;
