-- ACTCI 분류별 적용 설정과 속성 템플릿의 누락을 조회한다.
-- 상세 속성 대상은 CLASSIFICATIONID 목록에서 변경한다.

-- name: ci-definition-classes
SELECT S.CLASSIFICATIONID,S.CLASSSTRUCTUREID,S.PARENT,S.DESCRIPTION,
(SELECT COUNT(*) FROM MAXIMO.CLASSSPEC C WHERE C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID) AS SPEC_ROWS,
(SELECT COUNT(*) FROM MAXIMO.CLASSSPEC C JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID AND U.OBJECTNAME='ACTCI' WHERE C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID) AS ACTCI_SPEC_ROWS,
(SELECT COUNT(*) FROM MAXIMO.CLASSSPEC C WHERE C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID AND EXISTS (SELECT 1 FROM MAXIMO.ASSETATTRIBUTE A WHERE A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID AND A.ASSETATTRID=C.ASSETATTRID)) AS ATTRIBUTE_MATCH
FROM MAXIMO.CLASSSTRUCTURE S
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH W WHERE W.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID AND W.OBJECTNAME='ACTCI')
ORDER BY S.CLASSIFICATIONID;

-- name: ci-definition-missing-attribute-ids
SELECT S.CLASSIFICATIONID,COUNT(*) AS SPEC_ROWS,COUNT(C.ASSETATTRIBUTEID) AS ID_NONNULL,
SUM(CASE WHEN C.ASSETATTRIBUTEID=0 THEN 1 ELSE 0 END) AS ZERO_IDS,
SUM(CASE WHEN (SELECT COUNT(*) FROM MAXIMO.ASSETATTRIBUTE A WHERE A.ASSETATTRID=C.ASSETATTRID)=1 THEN 1 ELSE 0 END) AS UNIQUE_NAME_MATCH
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','SERVICE.SERVICEINSTANCE')
GROUP BY S.CLASSIFICATIONID;

-- name: ci-definition-attributes
SELECT S.CLASSIFICATIONID,C.ASSETATTRID,A.DESCRIPTION,A.DATATYPE,C.SECTION,C.MEASUREUNITID,A.MEASUREUNITID AS ATTRIBUTE_UNIT,
C.DOMAINID,U.OBJECTNAME,U.MANDATORY,U.SEQUENCE,U.USEINSPEC,
U.DEFAULTALNVALUE,U.DEFAULTNUMVALUE,U.DEFAULTTABLEVALUE
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID AND U.OBJECTNAME='ACTCI'
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','APP.DB.DATABASESERVER','APP.DB.MSSQL.SQLSERVER',
'APP.DB.MSSQL.SQLSERVERDATABASE','APP.DB.DB2.DB2INSTANCE','APP.DB.ORACLE.ORACLEINSTANCE',
'SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM','SERVICE.SERVICEINSTANCE','PROCESS.BUSINESSSERVICE',
'APP.APPLICATION','NET.IPNETWORK','NET.VLAN','SYS.STORAGE.STORAGEARRAY')
ORDER BY S.CLASSIFICATIONID,C.ASSETATTRID;

-- name: ci-definition-name-search
SELECT K.TERM,COUNT(S.CLASSSTRUCTUREID) AS MATCHED_CLASSES
FROM (VALUES ('KUBERNET'),('K8S'),('DOCKER'),('CLOUD'),('EC2'),('VRF'),('STORAGEARRAY')) K(TERM)
LEFT JOIN MAXIMO.CLASSSTRUCTURE S ON
(UPPER(S.CLASSIFICATIONID) LIKE '%' || K.TERM || '%' OR UPPER(S.DESCRIPTION) LIKE '%' || K.TERM || '%')
AND EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH U WHERE U.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID AND U.OBJECTNAME='ACTCI')
GROUP BY K.TERM ORDER BY K.TERM;

-- name: ci-definition-missing-id-attributes
SELECT S.CLASSIFICATIONID,C.ASSETATTRID,A.DATATYPE,C.MEASUREUNITID,A.MEASUREUNITID AS ATTRIBUTE_UNIT
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRID=C.ASSETATTRID
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','SERVICE.SERVICEINSTANCE')
ORDER BY S.CLASSIFICATIONID,C.ASSETATTRID;

-- name: ci-definition-template-gaps
SELECT S.CLASSIFICATIONID,COUNT(*) AS SPEC_ROWS,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSSPECUSEWITH U WHERE U.CLASSSPECID=C.CLASSSPECID AND U.OBJECTNAME='ACTCI') THEN 1 ELSE 0 END) AS ACTCI_USE_ROWS,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.ASSETATTRIBUTE A WHERE A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID) THEN 1 ELSE 0 END) AS ATTRIBUTE_ID_ROWS,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.ASSETATTRIBUTE A WHERE A.ASSETATTRID=C.ASSETATTRID) THEN 1 ELSE 0 END) AS ATTRIBUTE_NAME_ROWS
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
WHERE EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH W WHERE W.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID AND W.OBJECTNAME='ACTCI')
GROUP BY S.CLASSIFICATIONID
HAVING SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSSPECUSEWITH U WHERE U.CLASSSPECID=C.CLASSSPECID AND U.OBJECTNAME='ACTCI') THEN 1 ELSE 0 END)<COUNT(*)
ORDER BY S.CLASSIFICATIONID;

-- name: ci-definition-rule-pairs
SELECT S.CLASSIFICATIONID AS SOURCE_CLASS,R.RELATIONNUM,T.CLASSIFICATIONID AS TARGET_CLASS,
R.CARDINALITY,R.CONTAINMENT,R.REVRELATIONSHIP,R.SWAPPED,L.USEWITH
FROM MAXIMO.RELATIONRULES R JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=R.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE T ON T.CLASSSTRUCTUREID=R.TARGETCLASS
JOIN MAXIMO.RELATION L ON L.RELATIONNUM=R.RELATIONNUM
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','APP.DB.DATABASESERVER','APP.DB.MSSQL.SQLSERVER',
'APP.DB.MSSQL.SQLSERVERDATABASE','SERVICE.SERVICEINSTANCE','SYS.VIRTUALCOMPUTERSYSTEM','SYS.COMPUTERSYSTEM')
AND T.CLASSIFICATIONID IN ('APP.DB.DATABASE','APP.DB.DATABASESERVER','APP.DB.MSSQL.SQLSERVER',
'APP.DB.MSSQL.SQLSERVERDATABASE','SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM','SERVICE.SERVICEINSTANCE')
ORDER BY S.CLASSIFICATIONID,R.RELATIONNUM,T.CLASSIFICATIONID;
