-- ACTCI 번호의 문자열 저장 여부와 숫자 PK를 구분한다. 읽기 전용 메타데이터 조회.
-- name: identifier-columns
SELECT TABNAME,COLNAME,TYPENAME,LENGTH,SCALE,NULLS,IDENTITY,DEFAULT
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA='MAXIMO'
AND ((TABNAME='ACTCI' AND COLNAME IN ('ACTCIID','ACTCINUM','GUID','CCIDISGUID'))
OR (TABNAME IN ('ACTCISPEC','CI') AND COLNAME='ACTCINUM')
OR (TABNAME='ACTCIRELATION' AND COLNAME IN ('SOURCECI','TARGETCI')))
ORDER BY TABNAME,COLNAME;

-- name: identifier-attributes
SELECT OBJECTNAME,ATTRIBUTENAME,MAXTYPE,LENGTH,SCALE,REQUIRED,DOMAINID,AUTOKEYNAME,DEFAULTVALUE,SAMEASOBJECT,SAMEASATTRIBUTE,CLASSNAME
FROM MAXIMO.MAXATTRIBUTE
WHERE (OBJECTNAME='ACTCI' AND ATTRIBUTENAME IN ('ACTCIID','ACTCINUM'))
OR (OBJECTNAME='ACTCISPEC' AND ATTRIBUTENAME='ACTCINUM')
OR (OBJECTNAME='ACTCIRELATION' AND ATTRIBUTENAME IN ('SOURCECI','TARGETCI'))
ORDER BY OBJECTNAME,ATTRIBUTENAME;

-- name: identifier-indexes
SELECT I.INDNAME,I.UNIQUERULE,C.COLNAME,C.COLSEQ
FROM SYSCAT.INDEXES I JOIN SYSCAT.INDEXCOLUSE C ON C.INDSCHEMA=I.INDSCHEMA AND C.INDNAME=I.INDNAME
WHERE I.TABSCHEMA='MAXIMO' AND I.TABNAME='ACTCI'
ORDER BY I.INDNAME,C.COLSEQ;

-- name: identifier-checks
SELECT CONSTNAME,TEXT FROM SYSCAT.CHECKS WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION');

-- name: identifier-triggers
SELECT TRIGNAME,TABNAME,TEXT FROM SYSCAT.TRIGGERS
WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION')
ORDER BY TABNAME,TRIGNAME;

-- name: identifier-autokey
SELECT * FROM MAXIMO.AUTOKEY WHERE AUTOKEYNAME='ACTCINUM';
