-- Computer 적재·BIOS 날짜 속성 등록에 필요한 기준정보 구조. 읽기 전용.
-- name: registration-columns
SELECT TABNAME,COLNAME,TYPENAME,LENGTH,SCALE,NULLS,DEFAULT
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('ASSETATTRIBUTE','CLASSSPEC','CLASSSPECUSEWITH','MAXSEQUENCE')
ORDER BY TABNAME,COLNO;

-- name: registration-sequences
SELECT * FROM MAXIMO.MAXSEQUENCE
WHERE TBNAME IN ('ACTCI','ACTCISPEC','ASSETATTRIBUTE','CLASSSPEC','CLASSSPECUSEWITH');

-- name: sequence-definitions
SELECT SEQNAME,START,INCREMENT,CYCLE FROM SYSCAT.SEQUENCES
WHERE SEQSCHEMA='MAXIMO' AND SEQNAME IN
('ACTCISEQ','ACTCISPECSEQ','ASSETATTRIBUTESEQ','CLASSSPECSEQ','CLASSSPECUSEWITHSEQ');

-- name: registration-template
SELECT C.APPLYDOWNHIER,C.CONTINUOUS,C.PLUSPISGLOBAL,U.OBJECTNAME,U.OBJECTVALUE,
U.SEQUENCE,U.USEINDESC,U.USEINSPEC,U.MANDATORY
FROM MAXIMO.CLASSSPEC C
JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID
JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=C.CLASSSTRUCTUREID
WHERE S.CLASSIFICATIONID='SYS.COMPUTERSYSTEM' AND C.ASSETATTRID='COMPUTERSYSTEM_ROMVERSION';
