-- ACTCI를 CI로 승격할 때 쓰는 범위 설정을 조회한다. 정본 테이블은 MAXIMO.CITEMPLATE다.
-- 화면은 「승격 범위」이며 TOPCICLASSID·TOPACTCICLASSID가 범위 하나를 가리킨다.
-- 대상 범위는 promotion-scope-detail 블록의 CLASSIFICATIONID 조건으로 바꾼다.
-- name: promotion-scope-tops
SELECT tc.CLASSIFICATIONID AS TOP_CI, ta.CLASSIFICATIONID AS TOP_ACTCI, COUNT(*) AS MAPPED_ROWS
FROM MAXIMO.CITEMPLATE t
LEFT JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.TOPCICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE ta ON ta.CLASSSTRUCTUREID = t.TOPACTCICLASSID
GROUP BY tc.CLASSIFICATIONID, ta.CLASSIFICATIONID
ORDER BY 1;

-- name: promotion-scope-detail
SELECT tc.CLASSIFICATIONID AS TOP_CI, c.CLASSIFICATIONID AS CI_CLASS,
    a.CLASSIFICATIONID AS ACTCI_CLASS, t.CITEMPLATEID, t.ROWSTAMP
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE a ON a.CLASSSTRUCTUREID = t.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.TOPCICLASSID
WHERE tc.CLASSIFICATIONID IN ('CI.COMPUTERSYSTEM', 'CI.VIRTUALCOMPUTERSYSTEM')
ORDER BY 1, 2, 3;

-- name: loaded-classes-in-scope
SELECT s.CLASSIFICATIONID AS LOADED_CLASS,
    (SELECT COUNT(*) FROM MAXIMO.CITEMPLATE t WHERE t.ACTCICLASSID = s.CLASSSTRUCTUREID) AS SCOPE_ROWS
FROM MAXIMO.CLASSSTRUCTURE s
WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM',
    'SYS.OPERATINGSYSTEM', 'SYS.FILESYSTEM', 'SYS.LOCALFILESYSTEM', 'NET.IPADDRESS', 'DEV.DISKDRIVE')
ORDER BY 1;

-- name: ci-class-with-multiple-actci
SELECT tc.CLASSIFICATIONID AS TOP_CI, c.CLASSIFICATIONID AS CI_CLASS, COUNT(*) AS ACTCI_COUNT
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.TOPCICLASSID
GROUP BY tc.CLASSIFICATIONID, c.CLASSIFICATIONID
HAVING COUNT(*) > 1
ORDER BY 1, 2;
