-- name: relation-count
SELECT RELATIONNUM, COUNT(*) AS CNT FROM MAXIMO.ACTCIRELATION GROUP BY RELATIONNUM ORDER BY RELATIONNUM;

-- name: relation-rows
SELECT ACTCIRELATIONID, SOURCECI, TARGETCI, RELATIONNUM, SWAPPED, CHANGEBY, ANCESTORCI, SOURCECIGUID, TARGETCIGUID FROM MAXIMO.ACTCIRELATION ORDER BY ACTCIRELATIONID;

-- name: sample-6001
SELECT ACTCIRELATIONID, SOURCECI, TARGETCI, RELATIONNUM, SWAPPED, CHANGEBY, CHANGEDATE FROM MAXIMO.ACTCIRELATION WHERE SOURCECI = 'D42:DEVICEOS:147' AND TARGETCI = 'D42:DEVICE:173';

-- name: orphan-check
SELECT COUNT(*) AS ORPHANS FROM MAXIMO.ACTCIRELATION r WHERE NOT EXISTS (SELECT 1 FROM MAXIMO.ACTCI s WHERE s.ACTCINUM = r.SOURCECI) OR NOT EXISTS (SELECT 1 FROM MAXIMO.ACTCI t WHERE t.ACTCINUM = r.TARGETCI);

-- name: rule-check
SELECT COUNT(*) AS NO_RULE FROM MAXIMO.ACTCIRELATION r JOIN MAXIMO.ACTCI s ON s.ACTCINUM = r.SOURCECI JOIN MAXIMO.ACTCI t ON t.ACTCINUM = r.TARGETCI WHERE NOT EXISTS (SELECT 1 FROM MAXIMO.RELATIONRULES x WHERE x.RELATIONNUM = r.RELATIONNUM AND x.SOURCECLASS = s.CLASSSTRUCTUREID AND x.TARGETCLASS = t.CLASSSTRUCTUREID);

-- name: class-pair-spread
SELECT sc.CLASSIFICATIONID AS SOURCE_CLASS, r.RELATIONNUM, tc.CLASSIFICATIONID AS TARGET_CLASS, COUNT(*) AS CNT FROM MAXIMO.ACTCIRELATION r JOIN MAXIMO.ACTCI s ON s.ACTCINUM = r.SOURCECI JOIN MAXIMO.ACTCI t ON t.ACTCINUM = r.TARGETCI JOIN MAXIMO.CLASSSTRUCTURE sc ON sc.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.CLASSSTRUCTUREID GROUP BY sc.CLASSIFICATIONID, r.RELATIONNUM, tc.CLASSIFICATIONID ORDER BY SOURCE_CLASS, TARGET_CLASS;

-- name: filesystem-array-fanout
SELECT r.TARGETCI, COUNT(DISTINCT r.SOURCECI) AS DEVICE_CNT FROM MAXIMO.ACTCIRELATION r WHERE r.TARGETCI LIKE 'D42:MOUNTPOINT:%' GROUP BY r.TARGETCI HAVING COUNT(DISTINCT r.SOURCECI) > 1 ORDER BY DEVICE_CNT DESC;
