-- 관계 정의와 분류별 관계 규칙의 메타데이터 및 적용 현황을 조회한다.

-- name: ci-relation-rule-objects
SELECT O.OBJECTNAME,O.DESCRIPTION,L.DESCRIPTION AS KO_DESCRIPTION
FROM MAXIMO.MAXOBJECT O LEFT JOIN MAXIMO.L_MAXOBJECT L ON L.OWNERID=O.MAXOBJECTID AND L.LANGCODE='KO'
WHERE O.OBJECTNAME IN ('RELATION','RELATIONRULES','CLASSIFICATION','CLASSANCESTOR') ORDER BY O.OBJECTNAME;

-- name: ci-relation-rule-columns
SELECT A.OBJECTNAME,A.ATTRIBUTENAME,L.TITLE,A.MAXTYPE,A.LENGTH,A.REQUIRED,A.PERSISTENT,A.DOMAINID,A.SAMEASOBJECT,A.SAMEASATTRIBUTE
FROM MAXIMO.MAXATTRIBUTE A LEFT JOIN MAXIMO.L_MAXATTRIBUTE L ON L.OWNERID=A.MAXATTRIBUTEID AND L.LANGCODE='KO'
WHERE A.OBJECTNAME IN ('RELATION','RELATIONRULES') ORDER BY A.OBJECTNAME,A.ATTRIBUTENAME;

-- name: ci-relation-rule-links
SELECT PARENT,NAME,CHILD,WHERECLAUSE FROM MAXIMO.MAXRELATIONSHIP
WHERE PARENT IN ('RELATION','RELATIONRULES') OR CHILD='RELATIONRULES'
ORDER BY PARENT,CHILD,NAME;

-- name: ci-relation-rule-counts
SELECT 'RELATION' AS TABNAME,COUNT(*) AS ROW_CNT FROM MAXIMO.RELATION
UNION ALL SELECT 'RELATIONRULES',COUNT(*) FROM MAXIMO.RELATIONRULES;

-- name: ci-relation-rule-scopes
SELECT U.OBJECTNAME,COUNT(*) AS RULE_ROWS,COUNT(DISTINCT R.RELATIONNUM) AS RELATIONS,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH T WHERE T.CLASSSTRUCTUREID=R.TARGETCLASS AND T.OBJECTNAME=U.OBJECTNAME) THEN 1 ELSE 0 END) AS TARGET_SCOPE_MATCH,
SUM(CASE WHEN R.CONTAINMENT=1 THEN 1 ELSE 0 END) AS CONTAINMENT_ROWS,
SUM(CASE WHEN R.REVRELATIONSHIP=1 THEN 1 ELSE 0 END) AS TARGET_PARENT_ROWS
FROM MAXIMO.RELATIONRULES R JOIN MAXIMO.CLASSUSEWITH U ON U.CLASSSTRUCTUREID=R.SOURCECLASS
WHERE U.OBJECTNAME IN ('ACTCI','CI') GROUP BY U.OBJECTNAME;

-- name: ci-relation-rule-domain
SELECT DOMAINID,VALUE,DESCRIPTION FROM MAXIMO.ALNDOMAIN
WHERE DOMAINID IN ('RELUSEWITH','CARDINALITY','RELATIONTYPE') ORDER BY DOMAINID,VALUE;

-- name: ci-relation-rule-existing-ci
SELECT C.RELATIONNUM,COUNT(*) AS ROW_CNT,
SUM(CASE WHEN EXISTS (SELECT 1 FROM MAXIMO.RELATIONRULES R WHERE R.RELATIONNUM=C.RELATIONNUM AND R.SOURCECLASS=S.CLASSSTRUCTUREID AND R.TARGETCLASS=T.CLASSSTRUCTUREID) THEN 1 ELSE 0 END) AS RULE_MATCH
FROM MAXIMO.CIRELATION C JOIN MAXIMO.CI S ON S.CINUM=C.SOURCECI JOIN MAXIMO.CI T ON T.CINUM=C.TARGETCI
GROUP BY C.RELATIONNUM;

-- name: ci-relation-rule-examples
SELECT S.CLASSIFICATIONID AS SOURCE_CLASS,R.RELATIONNUM,T.CLASSIFICATIONID AS TARGET_CLASS,
R.CARDINALITY,R.CONTAINMENT,R.REVRELATIONSHIP,R.SWAPPED,L.USEWITH
FROM MAXIMO.RELATIONRULES R
JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=R.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE T ON T.CLASSSTRUCTUREID=R.TARGETCLASS
JOIN MAXIMO.RELATION L ON L.RELATIONNUM=R.RELATIONNUM
WHERE S.CLASSIFICATIONID IN ('APP.DB.DATABASE','APP.DB.DATABASESERVER')
AND T.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','APP.DB.DATABASE','APP.DB.DATABASESERVER')
ORDER BY S.CLASSIFICATIONID,R.RELATIONNUM,T.CLASSIFICATIONID;
