-- Actual CI와 CI의 타겟 구조 및 분류·속성 정의를 비교한다.
-- 조사 대상 변경은 각 IN 목록에서 한다. 결과에는 메타데이터와 집계만 포함한다.

-- name: ci-objects
SELECT O.OBJECTNAME, O.DESCRIPTION, L.DESCRIPTION AS KO_DESCRIPTION
FROM MAXIMO.MAXOBJECT O
LEFT JOIN MAXIMO.L_MAXOBJECT L ON L.OWNERID=O.MAXOBJECTID AND L.LANGCODE='KO'
WHERE O.OBJECTNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSPEC','CLASSSTRUCTURE')
ORDER BY O.OBJECTNAME;

-- name: ci-attributes
SELECT A.OBJECTNAME,A.ATTRIBUTENAME,L.TITLE AS KO_TITLE,A.MAXTYPE,A.LENGTH,A.SCALE,
       A.REQUIRED,A.DEFAULTVALUE,A.PERSISTENT,A.DOMAINID,A.SAMEASOBJECT,A.SAMEASATTRIBUTE,
       A.AUTOKEYNAME,A.PRIMARYKEYCOLSEQ
FROM MAXIMO.MAXATTRIBUTE A
LEFT JOIN MAXIMO.L_MAXATTRIBUTE L ON L.OWNERID=A.MAXATTRIBUTEID AND L.LANGCODE='KO'
WHERE A.OBJECTNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSPEC','CLASSSTRUCTURE')
ORDER BY A.OBJECTNAME,A.ATTRIBUTENAME;

-- name: ci-physical-columns
SELECT TABNAME,COLNAME,TYPENAME,LENGTH,SCALE,NULLS,DEFAULT,IDENTITY
FROM SYSCAT.COLUMNS WHERE TABSCHEMA='MAXIMO' AND TABNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSPEC','CLASSSTRUCTURE','CLASSUSEWITH','CLASSSPECUSEWITH','ASSETATTRIBUTE','RELATION','SYNONYMDOMAIN','ALNDOMAIN','NUMERICDOMAIN','MAXSEQUENCE')
ORDER BY TABNAME,COLNO;

-- name: ci-indexes
SELECT I.TABNAME,I.INDNAME,I.UNIQUERULE,C.COLSEQ,C.COLNAME,C.COLORDER
FROM SYSCAT.INDEXES I JOIN SYSCAT.INDEXCOLUSE C ON C.INDSCHEMA=I.INDSCHEMA AND C.INDNAME=I.INDNAME
WHERE I.TABSCHEMA='MAXIMO' AND I.TABNAME IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSPEC','CLASSSTRUCTURE')
ORDER BY I.TABNAME,I.INDNAME,C.COLSEQ;

-- name: ci-relationships
SELECT PARENT,NAME,CHILD,WHERECLAUSE
FROM MAXIMO.MAXRELATIONSHIP
WHERE PARENT IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSPEC','CLASSSTRUCTURE') AND CHILD IN ('ACTCI','ACTCISPEC','ACTCIRELATION','CI','CISPEC','CIRELATION','CLASSSPEC','CLASSSTRUCTURE','CLASSIFICATION','CLASSUSEWITH','CLASSSPECUSEWITH','ASSETATTRIBUTE','RELATION','SYNONYMDOMAIN','ALNDOMAIN','NUMERICDOMAIN','MEASUREUNIT')
ORDER BY PARENT,CHILD,NAME;

-- name: ci-sequences
SELECT SEQNAME,SEQTYPE,START,INCREMENT,MINVALUE,MAXVALUE,CYCLE,CACHE
FROM SYSCAT.SEQUENCES WHERE SEQSCHEMA='MAXIMO'
AND SEQNAME IN ('ACTCISEQ','ACTCISPECSEQ','ACTCIRELATIONSEQ','CISEQ','CISPECSEQ','CIRELATIONSEQ','CLASSSPECSEQ','CLASSSTRUCTURESEQ')
ORDER BY SEQNAME;

-- name: ci-row-counts
SELECT 'ACTCI' AS TABLE_NAME,COUNT(*) AS ROW_CNT FROM MAXIMO.ACTCI
UNION ALL
SELECT 'ACTCISPEC',COUNT(*) FROM MAXIMO.ACTCISPEC
UNION ALL
SELECT 'ACTCIRELATION',COUNT(*) FROM MAXIMO.ACTCIRELATION
UNION ALL
SELECT 'CI',COUNT(*) FROM MAXIMO.CI
UNION ALL
SELECT 'CISPEC',COUNT(*) FROM MAXIMO.CISPEC
UNION ALL
SELECT 'CIRELATION',COUNT(*) FROM MAXIMO.CIRELATION
UNION ALL
SELECT 'CLASSSPEC',COUNT(*) FROM MAXIMO.CLASSSPEC
UNION ALL
SELECT 'CLASSSTRUCTURE',COUNT(*) FROM MAXIMO.CLASSSTRUCTURE
ORDER BY TABLE_NAME;

