-- Computer 스펙 확장과 저장 단위의 실제 기준정보 조사.
-- name: bios-attributes
SELECT ASSETATTRID,ASSETATTRIBUTEID,DESCRIPTION,DATATYPE,MEASUREUNITID
FROM MAXIMO.ASSETATTRIBUTE
WHERE UPPER(ASSETATTRID) LIKE '%BIOS%' OR UPPER(ASSETATTRID) LIKE '%ROMVERSION%'
ORDER BY ASSETATTRID;

-- name: measurement-units
SELECT * FROM MAXIMO.MEASUREUNIT
WHERE UPPER(MEASUREUNITID) LIKE '%BYTE%' OR UPPER(MEASUREUNITID) LIKE '%HZ%'
ORDER BY MEASUREUNITID;
