-- 현재 CI 분류와 Interface 확장 후보의 관계 규칙. 숫자 분류 ID는 고정하지 않는다.
-- name: classifications
SELECT c.CLASSSTRUCTUREID,c.CLASSIFICATIONID,c.DESCRIPTION,u.TOPLEVEL FROM MAXIMO.CLASSSTRUCTURE c JOIN MAXIMO.CLASSUSEWITH u ON u.CLASSSTRUCTUREID=c.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI' WHERE c.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM','SYS.OPERATINGSYSTEM','DEV.DISKDRIVE','SYS.FILESYSTEM','NET.IPADDRESS','NET.IPINTERFACE','SYS.CPU') ORDER BY c.CLASSIFICATIONID;
-- name: pair-rules
SELECT s.CLASSIFICATIONID AS SOURCE_CLASS,r.SOURCECLASS,r.RELATIONNUM,t.CLASSIFICATIONID AS TARGET_CLASS,r.TARGETCLASS,r.CARDINALITY,r.CONTAINMENT,r.REVRELATIONSHIP,r.SWAPPED,l.USEWITH,l.TYPE,l.DESCRIPTION
FROM MAXIMO.RELATIONRULES r JOIN MAXIMO.CLASSSTRUCTURE s ON s.CLASSSTRUCTUREID=r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE t ON t.CLASSSTRUCTUREID=r.TARGETCLASS JOIN MAXIMO.RELATION l ON l.RELATIONNUM=r.RELATIONNUM
WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM','SYS.OPERATINGSYSTEM','DEV.DISKDRIVE','SYS.FILESYSTEM','NET.IPADDRESS','NET.IPINTERFACE','SYS.CPU') AND t.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM','SYS.OPERATINGSYSTEM','DEV.DISKDRIVE','SYS.FILESYSTEM','NET.IPADDRESS','NET.IPINTERFACE','SYS.CPU')
AND EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u WHERE u.CLASSSTRUCTUREID=s.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI')
AND EXISTS (SELECT 1 FROM MAXIMO.CLASSUSEWITH u WHERE u.CLASSSTRUCTUREID=t.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI')
ORDER BY s.CLASSIFICATIONID,t.CLASSIFICATIONID,r.RELATIONNUM;
-- name: relation-columns
SELECT ATTRIBUTENAME,MAXTYPE,LENGTH,REQUIRED,PERSISTENT,DEFAULTVALUE,SAMEASOBJECT,SAMEASATTRIBUTE FROM MAXIMO.MAXATTRIBUTE WHERE OBJECTNAME='ACTCIRELATION' ORDER BY ATTRIBUTENAME;
-- name: relation-links
SELECT NAME,CHILD,WHERECLAUSE FROM MAXIMO.MAXRELATIONSHIP WHERE PARENT='ACTCIRELATION' ORDER BY NAME;
-- name: relation-indexes
SELECT i.INDNAME,i.UNIQUERULE,c.COLNAME,c.COLSEQ FROM SYSCAT.INDEXES i JOIN SYSCAT.INDEXCOLUSE c ON c.INDSCHEMA=i.INDSCHEMA AND c.INDNAME=i.INDNAME WHERE i.TABSCHEMA='MAXIMO' AND i.TABNAME='ACTCIRELATION' ORDER BY i.INDNAME,c.COLSEQ;
-- name: relation-sequence
SELECT SEQNAME,INCREMENT FROM SYSCAT.SEQUENCES WHERE SEQSCHEMA='MAXIMO' AND SEQNAME='ACTCIRELATIONSEQ';
-- name: rule-attribute-descriptions
SELECT a.OBJECTNAME,a.ATTRIBUTENAME,a.TITLE,a.REMARKS,l.TITLE AS KO_TITLE FROM MAXIMO.MAXATTRIBUTE a LEFT JOIN MAXIMO.L_MAXATTRIBUTE l ON l.OWNERID=a.MAXATTRIBUTEID AND l.LANGCODE='KO'
WHERE a.OBJECTNAME IN ('RELATIONRULES','ACTCIRELATION') AND a.ATTRIBUTENAME IN ('SWAPPED','REVRELATIONSHIP','CARDINALITY','CONTAINMENT') ORDER BY a.OBJECTNAME,a.ATTRIBUTENAME;
-- name: relation-definitions
SELECT RELATIONNUM,DESCRIPTION,TYPE,COMPRELATION,USEWITH,IMPACTON FROM MAXIMO.RELATION WHERE RELATIONNUM IN ('RELATION.CONTAINS','RELATION.INSTALLEDON','RELATION.RUNSON','RELATION.VIRTUALIZES','RELATION.BINDSTO','RELATION.ROUTESVIA','RELATION.BOOTSFROM','RELATION.MANAGES','CONTAINS','INSTALLEDON','RUNSON','VIRTUALIZES') ORDER BY RELATIONNUM;
-- name: other-device-rules
SELECT s.CLASSIFICATIONID AS SOURCE_CLASS,r.RELATIONNUM,t.CLASSIFICATIONID AS TARGET_CLASS,r.CARDINALITY,r.CONTAINMENT,r.REVRELATIONSHIP,r.SWAPPED FROM MAXIMO.RELATIONRULES r JOIN MAXIMO.CLASSSTRUCTURE s ON s.CLASSSTRUCTUREID=r.SOURCECLASS JOIN MAXIMO.CLASSSTRUCTURE t ON t.CLASSSTRUCTUREID=r.TARGETCLASS WHERE (s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM') OR t.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')) AND r.RELATIONNUM IN ('RELATION.MANAGES','RELATION.MANAGEDVIA','RELATION.PHYSICALLYCONTAINS','RELATION.CONNECTS','RELATION.CONNECTEDTO') ORDER BY s.CLASSIFICATIONID,r.RELATIONNUM,t.CLASSIFICATIONID;
-- name: physical-constraints
SELECT CONSTNAME,TYPE FROM SYSCAT.TABCONST WHERE TABSCHEMA='MAXIMO' AND TABNAME='ACTCIRELATION';
