-- Computer 관련 분류를 계층 전체에서 탐색한다. 이름 접두어 대신 적용 객체를 함께 반환한다.
-- name: classification-tree
SELECT S.CLASSSTRUCTUREID,S.CLASSIFICATIONID,S.DESCRIPTION,S.PARENT,P.CLASSIFICATIONID AS PARENT_NAME,
S.DISCLASSIFICATION,S.ORGID,S.SITEID,U.OBJECTNAME,U.TOPLEVEL,U.AUTOCREATECI,
(SELECT COUNT(*) FROM MAXIMO.CLASSSPEC C WHERE C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID) AS SPECS
FROM MAXIMO.CLASSSTRUCTURE S
LEFT JOIN MAXIMO.CLASSSTRUCTURE P ON P.CLASSSTRUCTUREID=S.PARENT
LEFT JOIN MAXIMO.CLASSUSEWITH U ON U.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
WHERE U.OBJECTNAME IN ('CI','ACTCI') OR S.CLASSIFICATIONID IN ('IT','GENCSYS','WSAPPSER','ZCSYS')
ORDER BY U.OBJECTNAME,S.CLASSIFICATIONID;

-- name: attribute-definitions
SELECT ASSETATTRID,DESCRIPTION,DATATYPE,MEASUREUNITID,DOMAINID
FROM MAXIMO.ASSETATTRIBUTE
WHERE UPPER(ASSETATTRID) LIKE '%MEMORY%' OR UPPER(ASSETATTRID) LIKE '%RAM%'
OR UPPER(ASSETATTRID) LIKE '%CPU%' OR UPPER(ASSETATTRID) LIKE '%BIOS%'
OR UPPER(ASSETATTRID) LIKE '%CORE%'
ORDER BY ASSETATTRID;
