-- 관계 이름이 비슷한 두 코드의 실제 분류쌍을 비교한다.
-- name: contains-definitions
SELECT RELATIONNUM,DESCRIPTION,TYPE,COMPRELATION,USEWITH,CLASSSTRUCTUREID FROM MAXIMO.RELATION WHERE RELATIONNUM IN ('CONTAINS','RELATION.CONTAINS') ORDER BY RELATIONNUM;
-- name: contains-rules
SELECT r.RELATIONNUM,s.CLASSIFICATIONID AS SOURCE_CLASS,r.SOURCECLASS,t.CLASSIFICATIONID AS TARGET_CLASS,r.TARGETCLASS,r.CARDINALITY,r.CONTAINMENT,r.REVRELATIONSHIP,r.SWAPPED FROM MAXIMO.RELATIONRULES r LEFT JOIN MAXIMO.CLASSSTRUCTURE s ON s.CLASSSTRUCTUREID=r.SOURCECLASS LEFT JOIN MAXIMO.CLASSSTRUCTURE t ON t.CLASSSTRUCTUREID=r.TARGETCLASS WHERE r.RELATIONNUM='CONTAINS' OR (r.RELATIONNUM='RELATION.CONTAINS' AND s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM') AND t.CLASSIFICATIONID IN ('DEV.DISKDRIVE','SYS.FILESYSTEM','NET.IPINTERFACE','SYS.CPU')) ORDER BY r.RELATIONNUM,s.CLASSIFICATIONID,t.CLASSIFICATIONID;
-- name: contains-rule-counts
SELECT l.RELATIONNUM,COUNT(r.RELATIONNUM) AS RULE_COUNT FROM MAXIMO.RELATION l LEFT JOIN MAXIMO.RELATIONRULES r ON r.RELATIONNUM=l.RELATIONNUM WHERE l.RELATIONNUM IN ('CONTAINS','RELATION.CONTAINS') GROUP BY l.RELATIONNUM;
