-- DB Instance, Application Component, Device의 분류·승격·관계 후보를 확인한다.
-- 블록 설명은 이 머리말에만 적는다. 블록 사이 주석은 앞 블록 SQL 뒤에 붙는다.
--
-- db-engine-ci-specs            승격 대상 CI 분류가 제공하는 속성 템플릿. ACTCI 수집 속성의 대조 기준.
-- db-engine-spec-union          CI 4개 분류의 속성 합집합과 ACTCI 보유 여부를 한 행에서 대조.
-- db-engine-device-rule-flags   db-engine-device-rules 에 REVRELATIONSHIP·SWAPPED 를 더한 설정 원문.
-- db-instance-database-rules    Instance -> Database 분류쌍 규칙. 0건이면 등록 전까지 적재 불가.

-- name: db-app-actci-classes
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    s.DESCRIPTION,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPECUSEWITH u
      WHERE u.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
        AND u.OBJECTNAME = 'ACTCI' AND u.USEINSPEC = 1) AS ACTCI_SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'ACTCI'
)
AND (
    s.CLASSIFICATIONID LIKE 'APP.%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%APPLICATION%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%DATABASE%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%WEB%SERVER%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: db-app-selected-specs
SELECT s.CLASSIFICATIONID,
    c.ASSETATTRID,
    a.DESCRIPTION,
    a.DATATYPE,
    c.SECTION,
    u.SEQUENCE,
    u.MANDATORY,
    u.USEINSPEC
FROM MAXIMO.CLASSSTRUCTURE s
JOIN MAXIMO.CLASSSPEC c ON c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE a
  ON a.ASSETATTRIBUTEID = c.ASSETATTRIBUTEID
 AND a.ASSETATTRID = c.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH u
  ON u.CLASSSPECID = c.CLASSSPECID
 AND u.OBJECTNAME = 'ACTCI'
WHERE s.CLASSIFICATIONID IN (
    'APP.APPLICATION',
    'APP.DB.DATABASESERVER',
    'APP.WEB.WEBSERVER',
    'APP.APPSERVER',
    'APP.GENERICAPPSERVER',
    'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION'
)
ORDER BY s.CLASSIFICATIONID, c.ASSETATTRID;

-- name: db-app-ci-classes
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    s.DESCRIPTION,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'CI'
)
AND (
    s.CLASSIFICATIONID LIKE 'CI.%APP%'
    OR s.CLASSIFICATIONID LIKE 'CI.%DB%'
    OR s.CLASSIFICATIONID LIKE 'CI.%WEB%'
    OR UPPER(s.DESCRIPTION) LIKE '%APPLICATION%'
    OR UPPER(s.DESCRIPTION) LIKE '%DATABASE%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: db-app-promotion
SELECT a.CLASSIFICATIONID AS ACTCI_CLASS,
    c.CLASSIFICATIONID AS CI_CLASS,
    t.*
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE a ON a.CLASSSTRUCTUREID = t.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
WHERE a.CLASSIFICATIONID IN (
    'APP.APPLICATION',
    'APP.DB.DATABASESERVER',
    'APP.WEB.WEBSERVER',
    'APP.APPSERVER',
    'APP.GENERICAPPSERVER',
    'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION'
)
ORDER BY a.CLASSIFICATIONID, c.CLASSIFICATIONID;

-- name: db-app-device-rules
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    r.RELATIONNUM,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.CARDINALITY,
    r.CONTAINMENT,
    r.REVRELATIONSHIP,
    r.SWAPPED,
    r.PROPAGATECHANGE
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.APPLICATION', 'APP.DB.DATABASESERVER', 'APP.WEB.WEBSERVER',
    'APP.APPSERVER', 'APP.GENERICAPPSERVER', 'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION',
    'SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM'
)
AND ts.CLASSIFICATIONID IN (
    'APP.APPLICATION', 'APP.DB.DATABASESERVER', 'APP.WEB.WEBSERVER',
    'APP.APPSERVER', 'APP.GENERICAPPSERVER', 'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION',
    'SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM'
)
ORDER BY ss.CLASSIFICATIONID, r.RELATIONNUM, ts.CLASSIFICATIONID;

-- name: db-app-promotion-targets
SELECT tc.CLASSIFICATIONID AS TOP_CI,
    c.CLASSIFICATIONID AS CI_CLASS,
    a.CLASSIFICATIONID AS ACTCI_CLASS,
    t.CITEMPLATEID
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE a ON a.CLASSSTRUCTUREID = t.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.TOPCICLASSID
WHERE c.CLASSIFICATIONID IN ('CI.APPSERVER', 'CI.DATABASESERVER', 'CI.WEBSERVER')
ORDER BY c.CLASSIFICATIONID, a.CLASSIFICATIONID;

-- name: db-engine-classes
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPECUSEWITH u
      WHERE u.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
        AND u.OBJECTNAME = 'ACTCI' AND u.USEINSPEC = 1) AS ACTCI_SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'ACTCI'
)
AND (
    s.CLASSIFICATIONID IN (
        'APP.DB.DATABASESERVER',
        'APP.DB.GENERICDATABASESERVER',
        'APP.DB.DB2.DB2INSTANCE',
        'APP.DB.ORACLE.ORACLEINSTANCE',
        'APP.DB.MSSQL.SQLSERVER'
    )
    OR UPPER(s.CLASSIFICATIONID) LIKE '%POSTGRE%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: db-engine-device-rules
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    r.RELATIONNUM,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.CARDINALITY,
    r.CONTAINMENT
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.DB.DATABASESERVER',
    'APP.DB.GENERICDATABASESERVER',
    'APP.DB.DB2.DB2INSTANCE',
    'APP.DB.ORACLE.ORACLEINSTANCE',
    'APP.DB.MSSQL.SQLSERVER'
)
AND ts.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM')
ORDER BY ss.CLASSIFICATIONID, ts.CLASSIFICATIONID, r.RELATIONNUM;

-- name: db-engine-promotion
SELECT a.CLASSIFICATIONID AS ACTCI_CLASS,
    c.CLASSIFICATIONID AS CI_CLASS,
    tc.CLASSIFICATIONID AS TOP_CI,
    t.CITEMPLATEID
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE a ON a.CLASSSTRUCTUREID = t.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.TOPCICLASSID
WHERE a.CLASSIFICATIONID IN (
    'APP.DB.DATABASESERVER',
    'APP.DB.GENERICDATABASESERVER',
    'APP.DB.DB2.DB2INSTANCE',
    'APP.DB.ORACLE.ORACLEINSTANCE',
    'APP.DB.MSSQL.SQLSERVER'
)
ORDER BY a.CLASSIFICATIONID, c.CLASSIFICATIONID;

-- name: db-engine-ci-candidates
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'CI'
)
AND (
    s.CLASSIFICATIONID IN ('CI.DATABASESERVER', 'CI.DB2INSTANCE')
    OR UPPER(s.CLASSIFICATIONID) LIKE '%ORACLE%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%SQLSERVER%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%POSTGRE%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: application-runtime-classes
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'ACTCI'
)
AND (
    s.CLASSIFICATIONID IN (
        'APP.APPLICATION', 'APP.APPSERVER', 'APP.GENERICAPPSERVER',
        'APP.J2EE.J2EESERVER', 'APP.WEB.WEBSERVER', 'APP.SOFTWAREINSTALLATION'
    )
    OR UPPER(s.CLASSIFICATIONID) LIKE '%TOMCAT%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: application-runtime-device-rules
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    r.RELATIONNUM,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.CARDINALITY,
    r.CONTAINMENT
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.APPLICATION', 'APP.APPSERVER', 'APP.GENERICAPPSERVER',
    'APP.J2EE.J2EESERVER', 'APP.WEB.WEBSERVER', 'APP.SOFTWAREINSTALLATION'
)
AND ts.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM')
ORDER BY ss.CLASSIFICATIONID, ts.CLASSIFICATIONID, r.RELATIONNUM;

-- name: application-runtime-all-outgoing-rules
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    r.RELATIONNUM,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.CARDINALITY,
    r.CONTAINMENT
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.APPLICATION', 'APP.APPSERVER', 'APP.GENERICAPPSERVER',
    'APP.J2EE.J2EESERVER', 'APP.WEB.WEBSERVER', 'APP.SOFTWAREINSTALLATION'
)
ORDER BY ss.CLASSIFICATIONID, r.RELATIONNUM, ts.CLASSIFICATIONID;

-- name: db-engine-ci-specs
SELECT s.CLASSIFICATIONID AS CI_CLASS,
    c.ASSETATTRID,
    c.SECTION,
    a.DATATYPE,
    a.MEASUREUNITID AS ATTR_UNIT,
    c.MEASUREUNITID AS SPEC_UNIT,
    a.DOMAINID,
    u.MANDATORY,
    u.USEINSPEC
FROM MAXIMO.CLASSSTRUCTURE s
JOIN MAXIMO.CLASSSPEC c ON c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
JOIN MAXIMO.ASSETATTRIBUTE a
    ON a.ASSETATTRIBUTEID = c.ASSETATTRIBUTEID
   AND a.ASSETATTRID = c.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH u
    ON u.CLASSSPECID = c.CLASSSPECID AND u.OBJECTNAME = 'CI'
WHERE s.CLASSIFICATIONID IN (
    'CI.DATABASESERVER',
    'CI.SQLSERVER',
    'CI.DB2INSTANCE',
    'CI.ORACLEINSTANCE'
)
ORDER BY s.CLASSIFICATIONID, c.ASSETATTRID;

-- name: db-engine-spec-union
SELECT u.ASSETATTRID,
    MAX(CASE WHEN u.CI_CLASS = 'CI.DATABASESERVER' THEN 1 ELSE 0 END) AS CI_DBSERVER,
    MAX(CASE WHEN u.CI_CLASS = 'CI.SQLSERVER' THEN 1 ELSE 0 END) AS CI_SQLSERVER,
    MAX(CASE WHEN u.CI_CLASS = 'CI.DB2INSTANCE' THEN 1 ELSE 0 END) AS CI_DB2INSTANCE,
    MAX(CASE WHEN u.CI_CLASS = 'CI.ORACLEINSTANCE' THEN 1 ELSE 0 END) AS CI_ORACLEINSTANCE,
    MAX(u.DATATYPE) AS DATATYPE,
    MAX(CASE WHEN u.ACTCI_CLASS = 'APP.DB.GENERICDATABASESERVER' THEN 1 ELSE 0 END) AS ACT_GENERIC,
    MAX(CASE WHEN u.ACTCI_CLASS = 'APP.DB.DATABASESERVER' THEN 1 ELSE 0 END) AS ACT_DBSERVER,
    MAX(CASE WHEN u.ACTCI_CLASS = 'APP.DB.MSSQL.SQLSERVER' THEN 1 ELSE 0 END) AS ACT_SQLSERVER,
    MAX(CASE WHEN u.ACTCI_CLASS = 'APP.DB.DB2.DB2INSTANCE' THEN 1 ELSE 0 END) AS ACT_DB2INSTANCE,
    MAX(CASE WHEN u.ACTCI_CLASS = 'APP.DB.ORACLE.ORACLEINSTANCE' THEN 1 ELSE 0 END) AS ACT_ORACLEINSTANCE
FROM (
    SELECT s.CLASSIFICATIONID AS CI_CLASS,
        CAST(NULL AS VARCHAR(60)) AS ACTCI_CLASS,
        c.ASSETATTRID,
        a.DATATYPE
    FROM MAXIMO.CLASSSTRUCTURE s
    JOIN MAXIMO.CLASSSPEC c ON c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
    JOIN MAXIMO.ASSETATTRIBUTE a
        ON a.ASSETATTRIBUTEID = c.ASSETATTRIBUTEID
       AND a.ASSETATTRID = c.ASSETATTRID
    WHERE s.CLASSIFICATIONID IN (
        'CI.DATABASESERVER', 'CI.SQLSERVER', 'CI.DB2INSTANCE', 'CI.ORACLEINSTANCE'
    )
    UNION ALL
    SELECT CAST(NULL AS VARCHAR(60)) AS CI_CLASS,
        s.CLASSIFICATIONID AS ACTCI_CLASS,
        c.ASSETATTRID,
        a.DATATYPE
    FROM MAXIMO.CLASSSTRUCTURE s
    JOIN MAXIMO.CLASSSPEC c ON c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
    JOIN MAXIMO.ASSETATTRIBUTE a
        ON a.ASSETATTRIBUTEID = c.ASSETATTRIBUTEID
       AND a.ASSETATTRID = c.ASSETATTRID
    WHERE s.CLASSIFICATIONID IN (
        'APP.DB.GENERICDATABASESERVER', 'APP.DB.DATABASESERVER',
        'APP.DB.MSSQL.SQLSERVER', 'APP.DB.DB2.DB2INSTANCE', 'APP.DB.ORACLE.ORACLEINSTANCE'
    )
) u
GROUP BY u.ASSETATTRID
ORDER BY u.ASSETATTRID;

-- name: db-engine-device-rule-flags
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.RELATIONNUM,
    r.CARDINALITY,
    r.CONTAINMENT,
    r.REVRELATIONSHIP,
    r.SWAPPED
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.DB.DATABASESERVER',
    'APP.DB.GENERICDATABASESERVER',
    'APP.DB.DB2.DB2INSTANCE',
    'APP.DB.ORACLE.ORACLEINSTANCE',
    'APP.DB.MSSQL.SQLSERVER'
)
AND ts.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM')
ORDER BY ss.CLASSIFICATIONID, ts.CLASSIFICATIONID, r.RELATIONNUM;

-- name: db-instance-database-rules
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.RELATIONNUM,
    r.CARDINALITY,
    r.CONTAINMENT
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.DB.DATABASESERVER',
    'APP.DB.GENERICDATABASESERVER',
    'APP.DB.DB2.DB2INSTANCE',
    'APP.DB.ORACLE.ORACLEINSTANCE',
    'APP.DB.MSSQL.SQLSERVER'
)
AND ts.CLASSIFICATIONID = 'APP.DB.DATABASE'
ORDER BY ss.CLASSIFICATIONID, r.RELATIONNUM;
