-- DB Instance, Application Component, Device의 분류·승격·관계 후보를 확인한다.

-- name: db-app-actci-classes
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    s.DESCRIPTION,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPECUSEWITH u
      WHERE u.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
        AND u.OBJECTNAME = 'ACTCI' AND u.USEINSPEC = 1) AS ACTCI_SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'ACTCI'
)
AND (
    s.CLASSIFICATIONID LIKE 'APP.%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%APPLICATION%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%DATABASE%'
    OR UPPER(s.CLASSIFICATIONID) LIKE '%WEB%SERVER%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: db-app-selected-specs
SELECT s.CLASSIFICATIONID,
    c.ASSETATTRID,
    a.DESCRIPTION,
    a.DATATYPE,
    c.SECTION,
    u.SEQUENCE,
    u.MANDATORY,
    u.USEINSPEC
FROM MAXIMO.CLASSSTRUCTURE s
JOIN MAXIMO.CLASSSPEC c ON c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE a
  ON a.ASSETATTRIBUTEID = c.ASSETATTRIBUTEID
 AND a.ASSETATTRID = c.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH u
  ON u.CLASSSPECID = c.CLASSSPECID
 AND u.OBJECTNAME = 'ACTCI'
WHERE s.CLASSIFICATIONID IN (
    'APP.APPLICATION',
    'APP.DB.DATABASESERVER',
    'APP.WEB.WEBSERVER',
    'APP.APPSERVER',
    'APP.GENERICAPPSERVER',
    'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION'
)
ORDER BY s.CLASSIFICATIONID, c.ASSETATTRID;

-- name: db-app-ci-classes
SELECT s.CLASSIFICATIONID,
    s.CLASSSTRUCTUREID,
    s.PARENT,
    s.DESCRIPTION,
    (SELECT COUNT(*) FROM MAXIMO.CLASSSPEC c
      WHERE c.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID) AS SPEC_COUNT
FROM MAXIMO.CLASSSTRUCTURE s
WHERE EXISTS (
    SELECT 1 FROM MAXIMO.CLASSUSEWITH w
    WHERE w.CLASSSTRUCTUREID = s.CLASSSTRUCTUREID
      AND w.OBJECTNAME = 'CI'
)
AND (
    s.CLASSIFICATIONID LIKE 'CI.%APP%'
    OR s.CLASSIFICATIONID LIKE 'CI.%DB%'
    OR s.CLASSIFICATIONID LIKE 'CI.%WEB%'
    OR UPPER(s.DESCRIPTION) LIKE '%APPLICATION%'
    OR UPPER(s.DESCRIPTION) LIKE '%DATABASE%'
)
ORDER BY s.CLASSIFICATIONID;

-- name: db-app-promotion
SELECT a.CLASSIFICATIONID AS ACTCI_CLASS,
    c.CLASSIFICATIONID AS CI_CLASS,
    t.*
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE a ON a.CLASSSTRUCTUREID = t.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
WHERE a.CLASSIFICATIONID IN (
    'APP.APPLICATION',
    'APP.DB.DATABASESERVER',
    'APP.WEB.WEBSERVER',
    'APP.APPSERVER',
    'APP.GENERICAPPSERVER',
    'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION'
)
ORDER BY a.CLASSIFICATIONID, c.CLASSIFICATIONID;

-- name: db-app-device-rules
SELECT ss.CLASSIFICATIONID AS SOURCE_CLASS,
    r.RELATIONNUM,
    ts.CLASSIFICATIONID AS TARGET_CLASS,
    r.CARDINALITY,
    r.CONTAINMENT,
    r.REVRELATIONSHIP,
    r.SWAPPED,
    r.PROPAGATECHANGE
FROM MAXIMO.RELATIONRULES r
JOIN MAXIMO.CLASSSTRUCTURE ss ON ss.CLASSSTRUCTUREID = r.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE ts ON ts.CLASSSTRUCTUREID = r.TARGETCLASS
WHERE ss.CLASSIFICATIONID IN (
    'APP.APPLICATION', 'APP.DB.DATABASESERVER', 'APP.WEB.WEBSERVER',
    'APP.APPSERVER', 'APP.GENERICAPPSERVER', 'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION',
    'SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM'
)
AND ts.CLASSIFICATIONID IN (
    'APP.APPLICATION', 'APP.DB.DATABASESERVER', 'APP.WEB.WEBSERVER',
    'APP.APPSERVER', 'APP.GENERICAPPSERVER', 'APP.J2EE.J2EESERVER',
    'APP.J2EE.J2EEAPPLICATION',
    'SYS.COMPUTERSYSTEM', 'SYS.VIRTUALCOMPUTERSYSTEM'
)
ORDER BY ss.CLASSIFICATIONID, r.RELATIONNUM, ts.CLASSIFICATIONID;

-- name: db-app-promotion-targets
SELECT tc.CLASSIFICATIONID AS TOP_CI,
    c.CLASSIFICATIONID AS CI_CLASS,
    a.CLASSIFICATIONID AS ACTCI_CLASS,
    t.CITEMPLATEID
FROM MAXIMO.CITEMPLATE t
JOIN MAXIMO.CLASSSTRUCTURE a ON a.CLASSSTRUCTUREID = t.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE c ON c.CLASSSTRUCTUREID = t.CICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID = t.TOPCICLASSID
WHERE c.CLASSIFICATIONID IN ('CI.APPSERVER', 'CI.DATABASESERVER', 'CI.WEBSERVER')
ORDER BY c.CLASSIFICATIONID, a.CLASSIFICATIONID;
