-- Device 신규 필드의 Target 후보와 승격 범위 확인.
-- name: candidate-attributes
SELECT ASSETATTRID,DESCRIPTION,DATATYPE,MEASUREUNITID
FROM MAXIMO.ASSETATTRIBUTE
WHERE UPPER(ASSETATTRID) LIKE '%ENDOF%' OR UPPER(ASSETATTRID) LIKE '%EOS%'
OR UPPER(ASSETATTRID) LIKE '%EOL%' OR UPPER(ASSETATTRID) LIKE '%SUPPORT%'
OR UPPER(ASSETATTRID) LIKE '%SYSNAME%' OR UPPER(ASSETATTRID) LIKE '%FIRMWARE%'
OR UPPER(ASSETATTRID) LIKE '%TRAY%' OR UPPER(ASSETATTRID) LIKE '%THREAD%'
OR ASSETATTRID IN ('PHYSICALPRINTER_TRAYCOUNT','PHYSICALPRINTER_FIRMWARENAME',
'PHYSICALPRINTER_FIRMWAREVERSION')
ORDER BY ASSETATTRID;
-- name: device-promotion
SELECT TC.CLASSIFICATIONID AS TOP_CI,C.CLASSIFICATIONID AS CI_CLASS,A.CLASSIFICATIONID AS ACTCI_CLASS
FROM MAXIMO.CITEMPLATE T
JOIN MAXIMO.CLASSSTRUCTURE A ON A.CLASSSTRUCTUREID=T.ACTCICLASSID
JOIN MAXIMO.CLASSSTRUCTURE C ON C.CLASSSTRUCTUREID=T.CICLASSID
LEFT JOIN MAXIMO.CLASSSTRUCTURE TC ON TC.CLASSSTRUCTUREID=T.TOPCICLASSID
WHERE A.CLASSIFICATIONID IN ('SYS.GENERICSWITCH','SYS.GENERICROUTER','SYS.PRINTER','SYS.APPLIANCE.NETWORKSYSTEM')
ORDER BY 1,2,3;
-- name: snmp-specs
SELECT S.CLASSIFICATIONID,C.ASSETATTRID,A.DATATYPE,U.OBJECTNAME,U.USEINSPEC
FROM MAXIMO.CLASSSTRUCTURE S JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID
WHERE S.CLASSIFICATIONID='SYS.SNMPSYSTEMGROUP' ORDER BY C.ASSETATTRID;
