-- Device 통합 수집 후보의 실제 템플릿과 객체 적용 설정. 기준정보는 변경하지 않는다.
-- name: device-specs
SELECT S.CLASSIFICATIONID,C.CLASSSPECID,C.ASSETATTRID,C.ASSETATTRIBUTEID,
A.ASSETATTRID AS MATCHED_ATTRID,A.DESCRIPTION,A.DATATYPE,C.SECTION,C.MEASUREUNITID,
C.DOMAINID,C.INHERITEDFROMID,C.APPLYDOWNHIER,C.ORGID,C.SITEID,
U.OBJECTNAME,U.MANDATORY,U.SEQUENCE,U.USEINSPEC,
U.CLASSSTRUCTUREID AS USE_CLASS,U.ASSETATTRID AS USE_ATTR,U.SECTION AS USE_SECTION,U.ORGID AS USE_ORG,U.SITEID AS USE_SITE
FROM MAXIMO.CLASSSTRUCTURE S
JOIN MAXIMO.CLASSSPEC C ON C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.ASSETATTRIBUTE A ON A.ASSETATTRIBUTEID=C.ASSETATTRIBUTEID AND A.ASSETATTRID=C.ASSETATTRID
LEFT JOIN MAXIMO.CLASSSPECUSEWITH U ON U.CLASSSPECID=C.CLASSSPECID
WHERE S.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM',
'SYS.GENERICSWITCH','SYS.GENERICROUTER','SYS.APPLIANCE.NETWORKSYSTEM','SYS.PRINTER',
'NET.BRIDGE','NET.NETWORKING','CI.PRINTER','CI.COMPUTERSYSTEM','CI.ROUTER',
'CI.GENERIC_COMPUTERSYSTEM','CI.FCSWITCHFUNCTION','CI.IPSTORAGESWITCHFUNCTION')
ORDER BY S.CLASSIFICATIONID,C.ASSETATTRID,U.OBJECTNAME;
-- name: device-existing
SELECT S.CLASSIFICATIONID,COUNT(*) AS CNT
FROM MAXIMO.ACTCI A JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=A.CLASSSTRUCTUREID
GROUP BY S.CLASSIFICATIONID ORDER BY S.CLASSIFICATIONID;
-- name: printer-network-rules
SELECT S.CLASSIFICATIONID AS SOURCE_CLASS,R.RELATIONNUM,T.CLASSIFICATIONID AS TARGET_CLASS,
R.CARDINALITY,R.CONTAINMENT,R.REVRELATIONSHIP,R.SWAPPED
FROM MAXIMO.RELATIONRULES R
JOIN MAXIMO.CLASSSTRUCTURE S ON S.CLASSSTRUCTUREID=R.SOURCECLASS
JOIN MAXIMO.CLASSSTRUCTURE T ON T.CLASSSTRUCTUREID=R.TARGETCLASS
WHERE S.CLASSIFICATIONID IN ('SYS.PRINTER','SYS.GENERICSWITCH','SYS.GENERICROUTER','SYS.APPLIANCE.NETWORKSYSTEM')
OR T.CLASSIFICATIONID IN ('SYS.PRINTER','SYS.GENERICSWITCH','SYS.GENERICROUTER','SYS.APPLIANCE.NETWORKSYSTEM')
ORDER BY S.CLASSIFICATIONID,T.CLASSIFICATIONID,R.RELATIONNUM;
