-- Device 통합 수집의 Computer·네트워크·프린터 분류 후보와 적용 객체 탐색.
-- name: device-classes
SELECT S.CLASSIFICATIONID,S.CLASSSTRUCTUREID,S.DESCRIPTION,P.CLASSIFICATIONID AS PARENT_NAME,
S.ORGID,S.SITEID,U.OBJECTNAME,U.TOPLEVEL,U.AUTOCREATECI,
(SELECT COUNT(*) FROM MAXIMO.CLASSSPEC C WHERE C.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID) AS SPECS
FROM MAXIMO.CLASSSTRUCTURE S
LEFT JOIN MAXIMO.CLASSSTRUCTURE P ON P.CLASSSTRUCTUREID=S.PARENT
LEFT JOIN MAXIMO.CLASSUSEWITH U ON U.CLASSSTRUCTUREID=S.CLASSSTRUCTUREID
WHERE UPPER(S.CLASSIFICATIONID) LIKE '%COMPUTER%' OR UPPER(S.CLASSIFICATIONID) LIKE '%PRINTER%'
OR UPPER(S.CLASSIFICATIONID) LIKE '%SWITCH%' OR UPPER(S.CLASSIFICATIONID) LIKE '%ROUTER%'
OR UPPER(S.CLASSIFICATIONID) LIKE '%NETWORK%' OR S.CLASSIFICATIONID LIKE 'NET.%'
ORDER BY S.CLASSIFICATIONID,U.OBJECTNAME;
