-- DEPLOYEDASSET와 DPA 자식의 Maximo 기본키 및 Device42 자식 적재 여부를 확인한다.

-- name: source-target-map-table
SELECT TABSCHEMA, TABNAME
FROM SYSCAT.TABLES
WHERE TABNAME = 'SOURCE_TARGET_MAP'
ORDER BY TABSCHEMA;

-- name: primary-keys
SELECT OBJECTNAME, ATTRIBUTENAME, PRIMARYKEYCOLSEQ
FROM MAXIMO.MAXATTRIBUTE
WHERE OBJECTNAME IN (
    'DEPLOYEDASSET', 'DPACOMPUTER', 'DPACPU', 'DPADISK', 'DPADISPLAY',
    'DPALOGICALDRIVE', 'DPAMEDIAADAPTER', 'DPANETADAPTER', 'DPANETDEVICE',
    'DPANETPRINTER', 'DPAOS', 'DPASOFTWARE', 'DPASWSUITE', 'DPATCPIP'
)
  AND PRIMARYKEYCOLSEQ > 0
ORDER BY OBJECTNAME, PRIMARYKEYCOLSEQ;

-- name: device42-child-count
SELECT C.T, COUNT(*) AS ROW_COUNT
FROM (
    SELECT 'DPACOMPUTER' AS T, NODEID FROM MAXIMO.DPACOMPUTER
    UNION ALL SELECT 'DPACPU', NODEID FROM MAXIMO.DPACPU
    UNION ALL SELECT 'DPADISK', NODEID FROM MAXIMO.DPADISK
    UNION ALL SELECT 'DPADISPLAY', NODEID FROM MAXIMO.DPADISPLAY
    UNION ALL SELECT 'DPALOGICALDRIVE', NODEID FROM MAXIMO.DPALOGICALDRIVE
    UNION ALL SELECT 'DPAMEDIAADAPTER', NODEID FROM MAXIMO.DPAMEDIAADAPTER
    UNION ALL SELECT 'DPANETADAPTER', NODEID FROM MAXIMO.DPANETADAPTER
    UNION ALL SELECT 'DPANETDEVICE', NODEID FROM MAXIMO.DPANETDEVICE
    UNION ALL SELECT 'DPANETPRINTER', NODEID FROM MAXIMO.DPANETPRINTER
    UNION ALL SELECT 'DPAOS', NODEID FROM MAXIMO.DPAOS
    UNION ALL SELECT 'DPASOFTWARE', NODEID FROM MAXIMO.DPASOFTWARE
    UNION ALL SELECT 'DPASWSUITE', NODEID FROM MAXIMO.DPASWSUITE
    UNION ALL SELECT 'DPATCPIP', NODEID FROM MAXIMO.DPATCPIP
) C
JOIN MAXIMO.DEPLOYEDASSET D ON D.NODEID = C.NODEID
WHERE D.IMPORTSOURCE = 'Device42'
GROUP BY C.T
ORDER BY C.T;
