-- DPAOS / DPATCPIP / DPANETPRINTER / DPASWSUITE 기존 수집분의 값 관례를 확인한다.
-- Device42 적재 규칙의 근거가 아니라 타겟 도메인·단위·표기가 호환되는지
-- 비교하는 용도다.

-- name: os-sample
SELECT NAME, MANUFACTURER, VERSION, BUILD, SERVICEPACK, DESCRIPTION,
    CHARACTERSET1, LANGUAGE, LICENSEDORG, LICENSEDUSER, SERIALNUMBER
FROM MAXIMO.DPAOS
FETCH FIRST 20 ROWS ONLY;

-- name: os-coverage
SELECT COUNT(*) AS ROW_COUNT,
    COUNT(NAME) AS NAME_N, COUNT(MANUFACTURER) AS MANUFACTURER_N,
    COUNT(VERSION) AS VERSION_N, COUNT(BUILD) AS BUILD_N,
    COUNT(SERVICEPACK) AS SERVICEPACK_N, COUNT(DESCRIPTION) AS DESCRIPTION_N,
    COUNT(CHARACTERSET1) AS CHARSET_N, COUNT(LANGUAGE) AS LANGUAGE_N,
    COUNT(LICENSEDORG) AS LICORG_N, COUNT(LICENSEDUSER) AS LICUSER_N,
    COUNT(SERIALNUMBER) AS SERIAL_N
FROM MAXIMO.DPAOS;

-- name: tcpip-sample
SELECT TCPIPADDRESS, TCPIPNETMASK, GATEWAY, HOST, TCPIPDOMAIN,
    DHCPSERVER, DNSSERVER1, DNSSERVER2, DNSSERVER3,
    PRIMARYWINS, SECONDARYWINS
FROM MAXIMO.DPATCPIP
FETCH FIRST 20 ROWS ONLY;

-- name: tcpip-coverage
SELECT COUNT(*) AS ROW_COUNT,
    COUNT(TCPIPADDRESS) AS ADDRESS_N, COUNT(TCPIPNETMASK) AS NETMASK_N,
    COUNT(GATEWAY) AS GATEWAY_N, COUNT(HOST) AS HOST_N,
    COUNT(TCPIPDOMAIN) AS DOMAIN_N, COUNT(DHCPSERVER) AS DHCP_N,
    COUNT(DNSSERVER1) AS DNS1_N, COUNT(PRIMARYWINS) AS WINS_N
FROM MAXIMO.DPATCPIP;

-- name: tcpip-netmask-values
SELECT COALESCE(TCPIPNETMASK, '<NULL>') AS TCPIPNETMASK, COUNT(*) AS ROW_COUNT
FROM MAXIMO.DPATCPIP
GROUP BY TCPIPNETMASK
ORDER BY ROW_COUNT DESC
FETCH FIRST 30 ROWS ONLY;

-- name: printer-sample
SELECT NETWORKADDRESS, NETMACADDR, CURRENTRAM, RAMUNIT, MAXRAM,
    NUMBEROFTRAYS, HORIZONTALDPI, VERTICALDPI, COLORDEPTHBIT,
    MAXLENGTH, MAXWIDTH, SIZEUNIT
FROM MAXIMO.DPANETPRINTER;

-- name: swsuite-sample
SELECT SUITENAME, MANUFACTURER, VERSION, PRODUCTID, SERIALNUMBER,
    LANGUAGE, LICENSEDORG, LICENSEDUSER, USAGECOUNT, DESCRIPTION
FROM MAXIMO.DPASWSUITE;
