-- DPASOFTWARE 기존 수집분의 값 관례와 변환 계열 구조를 확인한다. Device42
-- 적재 규칙의 근거가 아니라 타겟 도메인과 표기가 호환되는지 비교하는 용도다.
--
-- 블록
--   software-coverage  DPASOFTWARE 컬럼별 충전 건수
--   software-values    TYPE·LANGUAGE·USAGECOUNT·SUITEID 값 관례
--   software-key       자연키 후보의 유일성. INSTALLPATH 가 필요한 이유
--   master-tables      DPAM* 변환 계열의 실재 여부와 행 수
--   master-coverage    자식 이름이 변환 변형에 등록돼 있는지
--   device42-manufacturer-coverage  Device42 부모 제조사의 변환 변형 등록 여부

-- name: software-coverage
SELECT COUNT(*) AS ROWS_ALL,
    COUNT(DESCRIPTION) AS DESC_N, COUNT(TYPE) AS TYPE_N,
    COUNT(VERSION) AS VER_N, COUNT(INSTALLPATH) AS PATH_N,
    COUNT(INSTALLDATE) AS INSTDATE_N, COUNT(FIRSTENCOUNTERED1) AS FIRST_N,
    COUNT(LASTENCOUNTERED1) AS LAST_N, COUNT(LASTUSAGEDATE) AS LASTUSE_N,
    COUNT(USAGECOUNT) AS UCNT_N, COUNT(LANGUAGE) AS LANG_N,
    COUNT(LICENSEDORG) AS LORG_N, COUNT(LICENSEDUSER) AS LUSER_N,
    COUNT(SERIALNUMBER) AS SERIAL_N, COUNT(PRODUCTID) AS PRODID_N,
    COUNT(METRICID) AS METRIC_N, COUNT(SUITEID) AS SUITE_N,
    COUNT(TLOAMSOFTWAREID) AS TLOAM_N
FROM MAXIMO.DPASOFTWARE;

-- name: software-values
SELECT COALESCE(TYPE,'<NULL>') AS TYPE, COALESCE(LANGUAGE,'<NULL>') AS LANGUAGE,
    COALESCE(CAST(USAGECOUNT AS VARCHAR),'<NULL>') AS USAGECOUNT,
    COALESCE(CAST(SUITEID AS VARCHAR),'<NULL>') AS SUITEID,
    COUNT(*) AS N
FROM MAXIMO.DPASOFTWARE
GROUP BY TYPE, LANGUAGE, USAGECOUNT, SUITEID
ORDER BY N DESC
FETCH FIRST 20 ROWS ONLY;

-- name: software-key
SELECT COUNT(*) AS ROWS_ALL,
    COUNT(DISTINCT NODEID || '|' || SOFTWARENAME || '|' || COALESCE(VERSION,'')) AS K_NAME_VER,
    COUNT(DISTINCT NODEID || '|' || SOFTWARENAME || '|' || COALESCE(VERSION,'') || '|' || COALESCE(INSTALLPATH,'')) AS K_PLUS_PATH,
    COUNT(DISTINCT NODEID || '|' || CAST(TLOAMSOFTWAREID AS VARCHAR)) AS K_NODE_TLOAM
FROM MAXIMO.DPASOFTWARE;

-- name: master-tables
SELECT t.TABNAME, t.CARD
FROM SYSCAT.TABLES t
WHERE t.TABSCHEMA = 'MAXIMO' AND t.TYPE = 'T'
  AND (t.TABNAME LIKE 'DPAM%' OR t.TABNAME = 'DPASOFTWARE')
ORDER BY t.TABNAME;

-- name: master-coverage
SELECT 'DPASOFTWARE.SOFTWARENAME -> DPAMSOFTWARE' AS LINK, COUNT(*) AS ROWS_ALL, COUNT(m.SOFTWARENAME) AS MATCHED
FROM MAXIMO.DPASOFTWARE s LEFT JOIN MAXIMO.DPAMSOFTWARE m ON m.SOFTWARENAME = s.SOFTWARENAME
UNION ALL
SELECT 'DPASOFTWARE.MANUFACTURER -> DPAMMANUFACTURER', COUNT(*), COUNT(m.MANUFACTURERNAME)
FROM MAXIMO.DPASOFTWARE s LEFT JOIN MAXIMO.DPAMMANUFACTURER m ON m.MANUFACTURERNAME = s.MANUFACTURER
UNION ALL
SELECT 'DPAOS.NAME -> DPAMOS', COUNT(*), COUNT(m.OSNAME)
FROM MAXIMO.DPAOS s LEFT JOIN MAXIMO.DPAMOS m ON m.OSNAME = s.NAME
UNION ALL
SELECT 'DPACPU.MAKEMODEL -> DPAMPROCESSOR', COUNT(*), COUNT(m.PROCESSORNAME)
FROM MAXIMO.DPACPU s LEFT JOIN MAXIMO.DPAMPROCESSOR m ON m.PROCESSORNAME = s.MAKEMODEL
UNION ALL
SELECT 'DPANETADAPTER.MAKEMODEL -> DPAMADAPTER', COUNT(*), COUNT(m.ADAPTERNAME)
FROM MAXIMO.DPANETADAPTER s LEFT JOIN MAXIMO.DPAMADAPTER m ON m.ADAPTERNAME = s.MAKEMODEL
UNION ALL
SELECT 'DEPLOYEDASSET.MANUFACTURER -> DPAMMANUFACTURER', COUNT(*), COUNT(m.MANUFACTURERNAME)
FROM MAXIMO.DEPLOYEDASSET s LEFT JOIN MAXIMO.DPAMMANUFACTURER m ON m.MANUFACTURERNAME = s.MANUFACTURER;

-- name: device42-manufacturer-coverage
SELECT s.MANUFACTURER, COUNT(*) AS ROWS_ALL, COUNT(m.MANUFACTURERNAME) AS MATCHED
FROM MAXIMO.DEPLOYEDASSET s
LEFT JOIN MAXIMO.DPAMMANUFACTURER m ON m.MANUFACTURERNAME = s.MANUFACTURER
WHERE s.IMPORTSOURCE = 'Device42'
GROUP BY s.MANUFACTURER
ORDER BY ROWS_ALL DESC, s.MANUFACTURER;
