-- DPA 자식 테이블이 Maximo UI 뷰에 노출되기 위해 필요한 변환 데이터 등록 상태를
-- 확인한다. UI 는 자식 테이블이 아니라 뷰를 읽고, 뷰는 변환 변형과 INNER
-- 조인하므로 미등록 값이 있으면 행이 조용히 사라진다.
--
-- 블록
--   view-conversion-deps  뷰별로 어떤 변환 변형을 조인하는지
--   view-loss             자식 테이블 행수 대비 뷰 행수. 차이가 미표시 건수다
--   manufacturer-missing  DPAMMANUVARIANT 미등록 제조사
--   os-missing            DPAMOSVARIANT 미등록 OS 이름
--   processor-missing     DPAMPROCVARIANT 미등록 CPU 모델
--   adapter-missing       DPAMADPTVARIANT 미등록 네트워크·미디어 어댑터 모델
--   software-link         DPASOFTWARE 와 TLOAMSOFTWARE 연결 상태
--   conversion-counts     변환 대상·변환 변형 테이블 행수
--   tloam-profile         TLOAMSOFTWARE 카탈로그와 DPASOFTWARE 연결 형태
--   tloam-uniqueid-rule   기존 UNIQUEID 생성 규칙 일치 여부
--   tloam-dpam-names      TLOAMSOFTWARE 와 DPAMSOFTWARE 이름 집합 관계

-- name: view-conversion-deps
SELECT v.VIEWNAME,
    CASE WHEN LOWER(v.TEXT) LIKE '%dpammanuvariant%' THEN 'Y' ELSE '' END AS MANU,
    CASE WHEN LOWER(v.TEXT) LIKE '%dpamosvariant%' THEN 'Y' ELSE '' END AS OS,
    CASE WHEN LOWER(v.TEXT) LIKE '%dpamprocvariant%' THEN 'Y' ELSE '' END AS PROC,
    CASE WHEN LOWER(v.TEXT) LIKE '%dpamadptvariant%' THEN 'Y' ELSE '' END AS ADPT,
    CASE WHEN LOWER(v.TEXT) LIKE '%tloamsoftware%' THEN 'Y' ELSE '' END AS TLOAMSW
FROM SYSCAT.VIEWS v
WHERE v.VIEWSCHEMA = 'MAXIMO' AND LOWER(v.TEXT) LIKE '%dpam%'
ORDER BY v.VIEWNAME;

-- name: view-loss
SELECT 'DPACOMPUTER' AS BASE_TABLE, 'COMPUTERSYSTEM' AS UI_VIEW,
    (SELECT COUNT(*) FROM MAXIMO.DPACOMPUTER) AS TABLE_ROWS,
    (SELECT COUNT(*) FROM MAXIMO.COMPUTERSYSTEM) AS VIEW_ROWS FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPACPU', 'DPACCPU', (SELECT COUNT(*) FROM MAXIMO.DPACPU),
    (SELECT COUNT(*) FROM MAXIMO.DPACCPU) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPAOS', 'DPACOS', (SELECT COUNT(*) FROM MAXIMO.DPAOS),
    (SELECT COUNT(*) FROM MAXIMO.DPACOS) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPADISK', 'DPACDISK', (SELECT COUNT(*) FROM MAXIMO.DPADISK),
    (SELECT COUNT(*) FROM MAXIMO.DPACDISK) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPANETADAPTER', 'DPACNETADAPTER', (SELECT COUNT(*) FROM MAXIMO.DPANETADAPTER),
    (SELECT COUNT(*) FROM MAXIMO.DPACNETADAPTER) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPAMEDIAADAPTER', 'DPACMEDIAADAPTER', (SELECT COUNT(*) FROM MAXIMO.DPAMEDIAADAPTER),
    (SELECT COUNT(*) FROM MAXIMO.DPACMEDIAADAPTER) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPADISPLAY', 'DPACDISPLAY', (SELECT COUNT(*) FROM MAXIMO.DPADISPLAY),
    (SELECT COUNT(*) FROM MAXIMO.DPACDISPLAY) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPASWSUITE', 'DPACSWSUITE', (SELECT COUNT(*) FROM MAXIMO.DPASWSUITE),
    (SELECT COUNT(*) FROM MAXIMO.DPACSWSUITE) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPASOFTWARE', 'DPACSOFTWARE', (SELECT COUNT(*) FROM MAXIMO.DPASOFTWARE),
    (SELECT COUNT(*) FROM MAXIMO.DPACSOFTWARE) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPANETDEVICE', 'NETDEVICE', (SELECT COUNT(*) FROM MAXIMO.DPANETDEVICE),
    (SELECT COUNT(*) FROM MAXIMO.NETDEVICE) FROM SYSIBM.SYSDUMMY1
UNION ALL SELECT 'DPANETPRINTER', 'NETPRINTER', (SELECT COUNT(*) FROM MAXIMO.DPANETPRINTER),
    (SELECT COUNT(*) FROM MAXIMO.NETPRINTER) FROM SYSIBM.SYSDUMMY1;

-- name: manufacturer-missing
SELECT SRC_TABLE, MANUFACTURER, COUNT(*) AS N FROM (
    SELECT 'DEPLOYEDASSET' AS SRC_TABLE, d.MANUFACTURER
    FROM MAXIMO.DEPLOYEDASSET d
    LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = d.MANUFACTURER
    WHERE v.MANUFACTURERVAR IS NULL
    UNION ALL
    SELECT 'DPACPU', c.MANUFACTURER
    FROM MAXIMO.DPACPU c
    LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = c.MANUFACTURER
    WHERE v.MANUFACTURERVAR IS NULL
    UNION ALL
    SELECT 'DPAOS', o.MANUFACTURER
    FROM MAXIMO.DPAOS o
    LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = o.MANUFACTURER
    WHERE v.MANUFACTURERVAR IS NULL
    UNION ALL
    SELECT 'DPANETADAPTER', a.MANUFACTURER
    FROM MAXIMO.DPANETADAPTER a
    LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = a.MANUFACTURER
    WHERE v.MANUFACTURERVAR IS NULL
    UNION ALL
    SELECT 'DPAMEDIAADAPTER', m.MANUFACTURER
    FROM MAXIMO.DPAMEDIAADAPTER m
    LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = m.MANUFACTURER
    WHERE v.MANUFACTURERVAR IS NULL
) t
GROUP BY SRC_TABLE, MANUFACTURER
ORDER BY SRC_TABLE, N DESC;

-- name: os-missing
SELECT o.NAME, COUNT(*) AS N
FROM MAXIMO.DPAOS o
LEFT JOIN MAXIMO.DPAMOSVARIANT v ON v.OSVARIANT = o.NAME
WHERE v.OSVARIANT IS NULL
GROUP BY o.NAME
ORDER BY N DESC, o.NAME;

-- name: processor-missing
SELECT c.MAKEMODEL, COUNT(*) AS N
FROM MAXIMO.DPACPU c
LEFT JOIN MAXIMO.DPAMPROCVARIANT v ON v.PROCESSORVAR = c.MAKEMODEL
WHERE v.PROCESSORVAR IS NULL
GROUP BY c.MAKEMODEL
ORDER BY N DESC, c.MAKEMODEL;

-- name: adapter-missing
SELECT MAKEMODEL, COUNT(*) AS N
FROM (
    SELECT a.MAKEMODEL
    FROM MAXIMO.DPANETADAPTER a
    LEFT JOIN MAXIMO.DPAMADPTVARIANT v ON v.ADAPTERVARIANT = a.MAKEMODEL
    WHERE v.ADAPTERVARIANT IS NULL
    UNION ALL
    SELECT a.MAKEMODEL
    FROM MAXIMO.DPAMEDIAADAPTER a
    LEFT JOIN MAXIMO.DPAMADPTVARIANT v ON v.ADAPTERVARIANT = a.MAKEMODEL
    WHERE v.ADAPTERVARIANT IS NULL
) missing
GROUP BY MAKEMODEL
ORDER BY N DESC, MAKEMODEL;

-- name: software-link
SELECT CASE WHEN s.TLOAMSOFTWAREID IS NULL THEN 'TLOAMSOFTWAREID 없음'
            WHEN t.TLOAMSOFTWAREID IS NULL THEN 'TLOAMSOFTWARE 행 없음'
            WHEN v.MANUFACTURERVAR IS NULL THEN 'TLOAM 제조사 미등록'
            ELSE '노출됨' END AS LINK,
    COUNT(*) AS N
FROM MAXIMO.DPASOFTWARE s
LEFT JOIN MAXIMO.TLOAMSOFTWARE t ON t.TLOAMSOFTWAREID = s.TLOAMSOFTWAREID
LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = t.MANUFACTURER
GROUP BY CASE WHEN s.TLOAMSOFTWAREID IS NULL THEN 'TLOAMSOFTWAREID 없음'
              WHEN t.TLOAMSOFTWAREID IS NULL THEN 'TLOAMSOFTWARE 행 없음'
              WHEN v.MANUFACTURERVAR IS NULL THEN 'TLOAM 제조사 미등록'
              ELSE '노출됨' END
ORDER BY N DESC;

-- name: conversion-counts
SELECT 'DPAMMANUFACTURER' AS CONVERSION_TABLE, COUNT(*) AS N FROM MAXIMO.DPAMMANUFACTURER
UNION ALL SELECT 'DPAMMANUVARIANT', COUNT(*) FROM MAXIMO.DPAMMANUVARIANT
UNION ALL SELECT 'DPAMOS', COUNT(*) FROM MAXIMO.DPAMOS
UNION ALL SELECT 'DPAMOSVARIANT', COUNT(*) FROM MAXIMO.DPAMOSVARIANT
UNION ALL SELECT 'DPAMPROCESSOR', COUNT(*) FROM MAXIMO.DPAMPROCESSOR
UNION ALL SELECT 'DPAMPROCVARIANT', COUNT(*) FROM MAXIMO.DPAMPROCVARIANT
UNION ALL SELECT 'DPAMADAPTER', COUNT(*) FROM MAXIMO.DPAMADAPTER
UNION ALL SELECT 'DPAMADPTVARIANT', COUNT(*) FROM MAXIMO.DPAMADPTVARIANT
UNION ALL SELECT 'DPAMSOFTWARE', COUNT(*) FROM MAXIMO.DPAMSOFTWARE
UNION ALL SELECT 'DPAMSWVARIANT', COUNT(*) FROM MAXIMO.DPAMSWVARIANT
UNION ALL SELECT 'TLOAMSOFTWARE', COUNT(*) FROM MAXIMO.TLOAMSOFTWARE
ORDER BY CONVERSION_TABLE;

-- name: tloam-profile
SELECT COUNT(*) AS ROWS_ALL,
       COUNT(DISTINCT SWNAME) AS DISTINCT_NAMES,
       COUNT(DISTINCT SWNAME || '|' || COALESCE(VERSION, '')) AS DISTINCT_NAME_VERSION,
       COUNT(TARGETSOFTWAREID) AS TARGET_FILLED,
       COUNT(PRODUCTID) AS PRODUCT_FILLED,
       COUNT(EXTERNALID) AS EXTERNAL_FILLED,
       COUNT(CASE WHEN ROLE = 'SOFTWAREPRODUCT' THEN 1 END) AS PRODUCT_ROLE,
       COUNT(CASE WHEN ISIPLA = 0 AND ISPVU = 0 AND ISSUBCAP = 0
                   AND ISDELETED = 0 AND ISREVIEWED = 0 THEN 1 END) AS ZERO_FLAGS
FROM MAXIMO.TLOAMSOFTWARE;

-- name: tloam-uniqueid-rule
SELECT COUNT(*) AS ROWS_ALL,
       COUNT(CASE WHEN UNIQUEID =
           UPPER(TRIM(COALESCE(NULLIF(SWNAME, ''), 'UNKNOWN')))
           || '|'
           || UPPER(REPLACE(
               CASE
                   WHEN NULLIF(TRIM(VERSION), '') IS NULL
                    AND NULLIF(TRIM(RELEASE), '') IS NULL THEN 'UNKNOWN'
                   WHEN NULLIF(TRIM(RELEASE), '') IS NULL THEN TRIM(VERSION)
                   WHEN NULLIF(TRIM(VERSION), '') IS NULL THEN TRIM(RELEASE)
                   ELSE TRIM(VERSION) || '.' || TRIM(RELEASE)
               END, ' ', ''))
           || '|'
           || UPPER(TRIM(MANUFACTURER))
       THEN 1 END) AS MATCHED
FROM MAXIMO.TLOAMSOFTWARE;

-- name: tloam-dpam-names
SELECT (SELECT COUNT(DISTINCT SOFTWARENAME) FROM MAXIMO.DPAMSOFTWARE) AS DPAM_NAMES,
    (SELECT COUNT(DISTINCT SWNAME) FROM MAXIMO.TLOAMSOFTWARE) AS TLOAM_NAMES,
    (SELECT COUNT(*) FROM MAXIMO.TLOAMSOFTWARE t
     WHERE EXISTS (SELECT 1 FROM MAXIMO.DPAMSOFTWARE d
                   WHERE d.SOFTWARENAME = t.SWNAME)) AS TLOAM_ROWS_MATCHED,
    (SELECT COUNT(*) FROM MAXIMO.DPAMSOFTWARE d
     WHERE EXISTS (SELECT 1 FROM MAXIMO.TLOAMSOFTWARE t
                   WHERE t.SWNAME = d.SOFTWARENAME)) AS DPAM_ROWS_MATCHED
FROM SYSIBM.SYSDUMMY1;
