-- 자체 ID를 쓰는 DPA 자식 테이블의 Maximo 시퀀스와 현재 ID 범위를 확인한다.

-- name: target-sequences
SELECT SEQNAME, START, INCREMENT, NEXTCACHEFIRSTVALUE
FROM SYSCAT.SEQUENCES
WHERE SEQSCHEMA = 'MAXIMO'
  AND SEQNAME IN (
      'DPACPUSEQ',
      'DPADISKSEQ',
      'DPADISPLAYSEQ',
      'DPALOGICALDRIVESEQ',
      'DPAMEDIAADAPTERSEQ',
      'DPANETADAPTERSEQ',
      'DPAOSSEQ',
      'DPASOFTWARESEQ',
      'DPASWSUITESEQ',
      'DPATCPIPSEQ'
  )
ORDER BY SEQNAME;

-- name: target-id-ranges
SELECT 'DPACPU' AS TABLENAME, MIN(CPUID) AS MIN_ID,
       MAX(CPUID) AS MAX_ID, COUNT(*) AS ROW_COUNT
FROM MAXIMO.DPACPU
UNION ALL
SELECT 'DPADISK', MIN(DISKID), MAX(DISKID), COUNT(*)
FROM MAXIMO.DPADISK
UNION ALL
SELECT 'DPADISPLAY', MIN(DISPLAYID), MAX(DISPLAYID), COUNT(*)
FROM MAXIMO.DPADISPLAY
UNION ALL
SELECT 'DPALOGICALDRIVE', MIN(LOGICALDRIVEID), MAX(LOGICALDRIVEID), COUNT(*)
FROM MAXIMO.DPALOGICALDRIVE
UNION ALL
SELECT 'DPAMEDIAADAPTER', MIN(ADAPTERID), MAX(ADAPTERID), COUNT(*)
FROM MAXIMO.DPAMEDIAADAPTER
UNION ALL
SELECT 'DPANETADAPTER', MIN(ADAPTERID), MAX(ADAPTERID), COUNT(*)
FROM MAXIMO.DPANETADAPTER
UNION ALL
SELECT 'DPAOS', MIN(OSID), MAX(OSID), COUNT(*)
FROM MAXIMO.DPAOS
UNION ALL
SELECT 'DPASOFTWARE', MIN(SOFTWAREID), MAX(SOFTWAREID), COUNT(*)
FROM MAXIMO.DPASOFTWARE
UNION ALL
SELECT 'DPASWSUITE', MIN(DPASWSUITEID), MAX(DPASWSUITEID), COUNT(*)
FROM MAXIMO.DPASWSUITE
UNION ALL
SELECT 'DPATCPIP', MIN(TCPIPID), MAX(TCPIPID), COUNT(*)
FROM MAXIMO.DPATCPIP
ORDER BY TABLENAME;
