-- 자체 ID를 쓰는 DPA 자식 테이블의 Maximo 시퀀스와 현재 ID 범위를 확인한다.

-- name: target-sequences
SELECT SEQNAME, START, INCREMENT, NEXTCACHEFIRSTVALUE
FROM SYSCAT.SEQUENCES
WHERE SEQSCHEMA = 'MAXIMO'
  AND SEQNAME IN (
      'DPADISPLAYSEQ',
      'DPALOGICALDRIVESEQ',
      'DPANETADAPTERSEQ',
      'DPAMEDIAADAPTERSEQ'
  )
ORDER BY SEQNAME;

-- name: target-id-ranges
SELECT 'DPADISPLAY' AS TABLENAME, MIN(DISPLAYID) AS MIN_ID,
       MAX(DISPLAYID) AS MAX_ID, COUNT(*) AS ROW_COUNT
FROM MAXIMO.DPADISPLAY
UNION ALL
SELECT 'DPALOGICALDRIVE', MIN(LOGICALDRIVEID), MAX(LOGICALDRIVEID), COUNT(*)
FROM MAXIMO.DPALOGICALDRIVE
UNION ALL
SELECT 'DPANETADAPTER', MIN(ADAPTERID), MAX(ADAPTERID), COUNT(*)
FROM MAXIMO.DPANETADAPTER
UNION ALL
SELECT 'DPAMEDIAADAPTER', MIN(ADAPTERID), MAX(ADAPTERID), COUNT(*)
FROM MAXIMO.DPAMEDIAADAPTER
ORDER BY TABLENAME;
