-- 기존 수집분의 값 관례를 확인한다. Device42 적재 규칙의 근거가 아니라
-- 타겟 도메인과 단위가 호환되는지 비교하는 용도다.

-- name: logical-drive-values
SELECT COALESCE(DRIVETYPE, '<NULL>') AS DRIVETYPE,
    COALESCE(FILESYSTEM, '<NULL>') AS FILESYSTEM,
    COALESCE(SIZEUNIT, '<NULL>') AS SIZEUNIT,
    COMPRESSED,
    ENCRYPTED,
    COUNT(*) AS ROW_COUNT
FROM MAXIMO.DPALOGICALDRIVE
GROUP BY DRIVETYPE, FILESYSTEM, SIZEUNIT, COMPRESSED, ENCRYPTED
ORDER BY ROW_COUNT DESC
FETCH FIRST 100 ROWS ONLY;

-- name: net-adapter-values
SELECT COALESCE(ADAPTERTYPE, '<NULL>') AS ADAPTERTYPE,
    COALESCE(BANDWIDTHUNIT, '<NULL>') AS BANDWIDTHUNIT,
    COALESCE(PROTOCOL, '<NULL>') AS PROTOCOL,
    COUNT(*) AS ROW_COUNT
FROM MAXIMO.DPANETADAPTER
GROUP BY ADAPTERTYPE, BANDWIDTHUNIT, PROTOCOL
ORDER BY ROW_COUNT DESC
FETCH FIRST 100 ROWS ONLY;

-- name: media-adapter-values
SELECT COALESCE(MEDIATYPE, '<NULL>') AS MEDIATYPE,
    COALESCE(MEMORYTYPE, '<NULL>') AS MEMORYTYPE,
    COALESCE(RAMUNIT, '<NULL>') AS RAMUNIT,
    COALESCE(BUSTYPE, '<NULL>') AS BUSTYPE,
    COUNT(*) AS ROW_COUNT
FROM MAXIMO.DPAMEDIAADAPTER
GROUP BY MEDIATYPE, MEMORYTYPE, RAMUNIT, BUSTYPE
ORDER BY ROW_COUNT DESC
FETCH FIRST 100 ROWS ONLY;

-- name: net-adapter-sample
SELECT ADAPTERTYPE, BANDWIDTH, BANDWIDTHUNIT, DESCRIPTION, MAKEMODEL,
    MANUFACTURER, NETMACADDR1, NETMACADDR2, PORT, PROTOCOL
FROM MAXIMO.DPANETADAPTER
FETCH FIRST 20 ROWS ONLY;
