-- ASSETCLASS 별로 어떤 DPA 자식 테이블에 행이 붙는지, 노드 커버리지는 얼마인지 본다.

-- name: child-coverage
SELECT 'DPACOMPUTER' AS T, COUNT(DISTINCT NODEID) AS NODES, COUNT(*) AS ROW_CNT FROM MAXIMO.DPACOMPUTER
UNION ALL SELECT 'DPAOS', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPAOS
UNION ALL SELECT 'DPASOFTWARE', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPASOFTWARE
UNION ALL SELECT 'DPACPU', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPACPU
UNION ALL SELECT 'DPADISK', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPADISK
UNION ALL SELECT 'DPALOGICALDRIVE', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPALOGICALDRIVE
UNION ALL SELECT 'DPANETADAPTER', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPANETADAPTER
UNION ALL SELECT 'DPATCPIP', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPATCPIP
UNION ALL SELECT 'DPAMEDIAADAPTER', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPAMEDIAADAPTER
UNION ALL SELECT 'DPADISPLAY', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPADISPLAY
UNION ALL SELECT 'DPASWSUITE', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPASWSUITE
UNION ALL SELECT 'DPANETDEVICE', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPANETDEVICE
UNION ALL SELECT 'DPANETPRINTER', COUNT(DISTINCT NODEID), COUNT(*) FROM MAXIMO.DPANETPRINTER
ORDER BY 2 DESC;

-- name: assetclass-dist
SELECT ASSETCLASS,
       COALESCE(IMPORTSOURCE,'(null)') AS IMPORTSOURCE,
       COUNT(*) AS CNT
FROM MAXIMO.DEPLOYEDASSET
GROUP BY ASSETCLASS, IMPORTSOURCE
ORDER BY 3 DESC;

-- name: device42-parent-ids
SELECT SOURCEID, NODENAME, ASSETCLASS
FROM MAXIMO.DEPLOYEDASSET
WHERE IMPORTSOURCE = 'Device42'
ORDER BY ASSETCLASS, SOURCEID;
