-- OS -> Computer ACTCI relations and their promotion results; no fixed source PK.
-- name: os-computer-promotion
SELECT ar.ACTCIRELATIONID,ar.SOURCECI AS SOURCE_ACTCINUM,ar.TARGETCI AS TARGET_ACTCINUM,
       ar.RELATIONNUM,ar.SWAPPED,
       sc.CLASSIFICATIONID AS SOURCE_ACT_CLASS,tc.CLASSIFICATIONID AS TARGET_ACT_CLASS,
       s.CINUM AS SOURCE_CINUM,t.CINUM AS TARGET_CINUM,
       cs.CLASSIFICATIONID AS SOURCE_CI_CLASS,ct.CLASSIFICATIONID AS TARGET_CI_CLASS,
       cr.CIRELATIONID,cr.PARENTCI,cr.ANCESTORCI
FROM MAXIMO.ACTCIRELATION ar
JOIN MAXIMO.ACTCI sa ON sa.ACTCINUM=ar.SOURCECI
JOIN MAXIMO.ACTCI ta ON ta.ACTCINUM=ar.TARGETCI
JOIN MAXIMO.CLASSSTRUCTURE sc ON sc.CLASSSTRUCTUREID=sa.CLASSSTRUCTUREID
JOIN MAXIMO.CLASSSTRUCTURE tc ON tc.CLASSSTRUCTUREID=ta.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.CI s ON s.ACTCINUM=sa.ACTCINUM
LEFT JOIN MAXIMO.CI t ON t.ACTCINUM=ta.ACTCINUM
LEFT JOIN MAXIMO.CLASSSTRUCTURE cs ON cs.CLASSSTRUCTUREID=s.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.CLASSSTRUCTURE ct ON ct.CLASSSTRUCTUREID=t.CLASSSTRUCTUREID
LEFT JOIN MAXIMO.CIRELATION cr ON cr.SOURCECI=s.CINUM AND cr.TARGETCI=t.CINUM AND cr.RELATIONNUM=ar.RELATIONNUM
WHERE ar.RELATIONNUM='RELATION.INSTALLEDON'
AND sc.CLASSIFICATIONID='SYS.OPERATINGSYSTEM'
AND tc.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
ORDER BY ar.ACTCIRELATIONID;
