-- 현행 적재 행·변환 값·소프트웨어 UI 선행조건을 확인한다.
-- Device42 post-load-audit.sql 결과와 집합으로 대조한다.

-- name: loaded-rows
SELECT 'DEPLOYEDASSET' AS ENTITY, CAST(NODEID AS VARCHAR(640)) AS TARGET_ID,
       CAST('' AS VARCHAR(640)) AS PARENT_ID
FROM MAXIMO.DEPLOYEDASSET
UNION ALL
SELECT 'DPACOMPUTER', CAST(NODEID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPACOMPUTER
UNION ALL
SELECT 'DPACPU', CAST(CPUID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPACPU
UNION ALL
SELECT 'DPADISK', CAST(DISKID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPADISK
UNION ALL
SELECT 'DPALOGICALDRIVE', CAST(LOGICALDRIVEID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPALOGICALDRIVE
UNION ALL
SELECT 'DPAMEDIAADAPTER', CAST(ADAPTERID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPAMEDIAADAPTER
UNION ALL
SELECT 'DPANETADAPTER', CAST(ADAPTERID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPANETADAPTER
UNION ALL
SELECT 'DPAOS', CAST(OSID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPAOS
UNION ALL
SELECT 'DPASOFTWARE', CAST(SOFTWAREID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPASOFTWARE
UNION ALL
SELECT 'DPATCPIP', CAST(TCPIPADDRESS AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPATCPIP
UNION ALL
SELECT 'DPANETDEVICE', CAST(NODEID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPANETDEVICE
UNION ALL
SELECT 'DPANETPRINTER', CAST(NODEID AS VARCHAR(640)), CAST(NODEID AS VARCHAR(640))
FROM MAXIMO.DPANETPRINTER
UNION ALL
SELECT 'TLOAMSOFTWARE', CAST(UNIQUEID AS VARCHAR(640)), CAST('' AS VARCHAR(640))
FROM MAXIMO.TLOAMSOFTWARE
ORDER BY ENTITY, TARGET_ID, PARENT_ID;

-- name: loaded-conversion-values
SELECT 'MANUFACTURER' AS DOMAIN, CAST(MANUFACTURERVAR AS VARCHAR(640)) AS VALUE
FROM MAXIMO.DPAMMANUVARIANT
UNION
SELECT 'OS', CAST(OSVARIANT AS VARCHAR(640))
FROM MAXIMO.DPAMOSVARIANT
UNION
SELECT 'PROCESSOR', CAST(PROCESSORVAR AS VARCHAR(640))
FROM MAXIMO.DPAMPROCVARIANT
UNION
SELECT 'ADAPTER', CAST(ADAPTERVARIANT AS VARCHAR(640))
FROM MAXIMO.DPAMADPTVARIANT
ORDER BY DOMAIN, VALUE;

-- name: loaded-conversion-target-values
SELECT 'MANUFACTURER' AS DOMAIN, CAST(MANUFACTURERNAME AS VARCHAR(640)) AS VALUE
FROM MAXIMO.DPAMMANUFACTURER
UNION
SELECT 'OS', CAST(OSNAME AS VARCHAR(640))
FROM MAXIMO.DPAMOS
UNION
SELECT 'PROCESSOR', CAST(PROCESSORNAME AS VARCHAR(640))
FROM MAXIMO.DPAMPROCESSOR
UNION
SELECT 'ADAPTER', CAST(ADAPTERNAME AS VARCHAR(640))
FROM MAXIMO.DPAMADAPTER
ORDER BY DOMAIN, VALUE;

-- name: device42-parent-summary
SELECT ASSETCLASS, COUNT(*) AS N,
       COUNT(CASE WHEN SOURCEID = CAST(NODEID AS VARCHAR(50)) THEN 1 END) AS DIRECT_SOURCE_ID,
       COUNT(CASE WHEN IMPORTSOURCE = 'Device42' THEN 1 END) AS DEVICE42_IMPORTSOURCE
FROM MAXIMO.DEPLOYEDASSET
WHERE HWDETECTIONTOOL = 'Device42'
GROUP BY ASSETCLASS
ORDER BY ASSETCLASS;

-- name: software-health
SELECT COUNT(*) AS DPA_ROWS,
       COUNT(s.TLOAMSOFTWAREID) AS HAS_TLOAMSOFTWAREID,
       COUNT(s.TLOAMPRODUCTID) AS HAS_TLOAMPRODUCTID,
       COUNT(CASE WHEN s.TLOAMSOFTWAREID = s.TLOAMPRODUCTID THEN 1 END) AS IDS_EQUAL,
       COUNT(t.TLOAMSOFTWAREID) AS CATALOG_MATCHED,
       COUNT(v.MANUFACTURERVAR) AS MANUFACTURER_MATCHED,
       COUNT(CASE WHEN resolved.TLOAMSOFTWAREID IS NOT NULL
                   AND v.MANUFACTURERVAR IS NOT NULL THEN 1 END) AS UI_ELIGIBLE
FROM MAXIMO.DPASOFTWARE s
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = s.NODEID
LEFT JOIN MAXIMO.TLOAMSOFTWARE t ON t.TLOAMSOFTWAREID = s.TLOAMSOFTWAREID
LEFT JOIN MAXIMO.TLOAMSOFTWARE resolved
       ON resolved.TLOAMSOFTWAREID = CASE
            WHEN t.TARGETSOFTWAREID IS NULL OR t.TARGETSOFTWAREID = 0
                THEN t.TLOAMSOFTWAREID
            ELSE t.TARGETSOFTWAREID
          END
LEFT JOIN MAXIMO.DPAMMANUVARIANT v ON v.MANUFACTURERVAR = resolved.MANUFACTURER
WHERE d.HWDETECTIONTOOL = 'Device42';

-- name: software-new-catalog
SELECT COUNT(*) AS NEW_CATALOG_ROWS,
       MIN(TLOAMSOFTWAREID) AS MIN_ID,
       MAX(TLOAMSOFTWAREID) AS MAX_ID,
       COUNT(CASE WHEN ROLE = 'SOFTWAREPRODUCT' THEN 1 END) AS PRODUCT_ROLE,
       COUNT(CASE WHEN ISIPLA = 0 AND ISPVU = 0 AND ISSUBCAP = 0
                   AND ISDELETED = 0 AND ISREVIEWED = 0 THEN 1 END) AS ZERO_FLAGS
FROM MAXIMO.TLOAMSOFTWARE
WHERE TLOAMSOFTWAREID >= 2175001;

-- name: software-ui-view
SELECT COUNT(*) AS UI_VIEW_ROWS,
       COUNT(DISTINCT v.SOFTWAREID) AS DISTINCT_SOFTWARE_IDS,
       COUNT(CASE WHEN v.TLOAMSOFTWAREID IS NOT NULL THEN 1 END) AS HAS_TLOAM_ID
FROM MAXIMO.DPACSOFTWARE v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42';

-- name: ui-view-summary
SELECT 'DPACOMPUTER' AS BASE_TABLE, 'COMPUTERSYSTEM' AS UI_VIEW, COUNT(*) AS N
FROM MAXIMO.COMPUTERSYSTEM v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPACPU', 'DPACCPU', COUNT(*)
FROM MAXIMO.DPACCPU v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPADISK', 'DPACDISK', COUNT(*)
FROM MAXIMO.DPACDISK v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPAMEDIAADAPTER', 'DPACMEDIAADAPTER', COUNT(*)
FROM MAXIMO.DPACMEDIAADAPTER v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPANETADAPTER', 'DPACNETADAPTER', COUNT(*)
FROM MAXIMO.DPACNETADAPTER v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPANETDEVICE', 'NETDEVICE', COUNT(*)
FROM MAXIMO.NETDEVICE v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPANETPRINTER', 'NETPRINTER', COUNT(*)
FROM MAXIMO.NETPRINTER v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPAOS', 'DPACOS', COUNT(*)
FROM MAXIMO.DPACOS v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
UNION ALL
SELECT 'DPASOFTWARE', 'DPACSOFTWARE', COUNT(*)
FROM MAXIMO.DPACSOFTWARE v
JOIN MAXIMO.DEPLOYEDASSET d ON d.NODEID = v.NODEID
WHERE d.HWDETECTIONTOOL = 'Device42'
ORDER BY BASE_TABLE;
