-- 현행 적재에서 사용하지 않는 DISCOVERY.SOURCE_TARGET_MAP의 잔존 상태를 확인한다.

-- name: map-columns
SELECT COLNO,
       COLNAME,
       TYPENAME,
       LENGTH,
       SCALE,
       NULLS,
       DEFAULT,
       IDENTITY,
       GENERATED
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DISCOVERY'
  AND TABNAME = 'SOURCE_TARGET_MAP'
ORDER BY COLNO;

-- name: map-constraints
SELECT C.CONSTNAME,
       C.TYPE,
       C.ENFORCED,
       K.COLNAME,
       K.COLSEQ
FROM SYSCAT.TABCONST C
LEFT JOIN SYSCAT.KEYCOLUSE K
  ON K.TABSCHEMA = C.TABSCHEMA
 AND K.TABNAME = C.TABNAME
 AND K.CONSTNAME = C.CONSTNAME
WHERE C.TABSCHEMA = 'DISCOVERY'
  AND C.TABNAME = 'SOURCE_TARGET_MAP'
ORDER BY C.CONSTNAME, K.COLSEQ;

-- name: map-indexes
SELECT INDSCHEMA,
       INDNAME,
       UNIQUERULE,
       COLNAMES
FROM SYSCAT.INDEXES
WHERE TABSCHEMA = 'DISCOVERY'
  AND TABNAME = 'SOURCE_TARGET_MAP'
ORDER BY INDNAME;

-- name: map-references
SELECT CONSTNAME,
       REFTABSCHEMA,
       REFTABNAME,
       DELETERULE,
       UPDATERULE
FROM SYSCAT.REFERENCES
WHERE TABSCHEMA = 'DISCOVERY'
  AND TABNAME = 'SOURCE_TARGET_MAP'
ORDER BY CONSTNAME;

-- name: map-sequences
SELECT SEQSCHEMA,
       SEQNAME,
       INCREMENT,
       NEXTCACHEFIRSTVALUE
FROM SYSCAT.SEQUENCES
WHERE SEQSCHEMA = 'DISCOVERY'
  AND SEQNAME LIKE '%SOURCE%TARGET%'
ORDER BY SEQNAME;

-- name: map-count
SELECT COUNT(*) AS ROW_COUNT
FROM DISCOVERY.SOURCE_TARGET_MAP;

-- name: map-object-count
SELECT SOURCE_SYSTEM,
       SOURCE_OBJECT,
       TARGET_SYSTEM,
       TARGET_OBJECT,
       COUNT(*) AS ROW_COUNT
FROM DISCOVERY.SOURCE_TARGET_MAP
GROUP BY SOURCE_SYSTEM, SOURCE_OBJECT, TARGET_SYSTEM, TARGET_OBJECT
ORDER BY SOURCE_SYSTEM, SOURCE_OBJECT, TARGET_SYSTEM, TARGET_OBJECT;

-- name: duplicate-source-key
SELECT SOURCE_SYSTEM,
       SOURCE_OBJECT,
       SOURCE_ID,
       COUNT(*) AS ROW_COUNT
FROM DISCOVERY.SOURCE_TARGET_MAP
GROUP BY SOURCE_SYSTEM, SOURCE_OBJECT, SOURCE_ID
HAVING COUNT(*) > 1
ORDER BY SOURCE_SYSTEM, SOURCE_OBJECT, SOURCE_ID;

-- name: duplicate-target-key
SELECT TARGET_SYSTEM,
       TARGET_OBJECT,
       TARGET_ID,
       COUNT(*) AS ROW_COUNT
FROM DISCOVERY.SOURCE_TARGET_MAP
GROUP BY TARGET_SYSTEM, TARGET_OBJECT, TARGET_ID
HAVING COUNT(*) > 1
ORDER BY TARGET_SYSTEM, TARGET_OBJECT, TARGET_ID;
