-- 대상 테이블의 한글 설명. 매핑 문서 최상단 한 줄에 사용한다.
-- 대상 변경은 IN 목록만 수정한다.

-- name: table-description
SELECT O.OBJECTNAME,
       L.DESCRIPTION AS KO_DESC
FROM MAXIMO.MAXOBJECT O
LEFT JOIN MAXIMO.L_MAXOBJECT L
       ON L.OWNERID = O.MAXOBJECTID
      AND L.LANGCODE = 'KO'
WHERE O.OBJECTNAME IN ('DEPLOYEDASSET','DPACOMPUTER','DPAOS','DPASOFTWARE',
                       'DPACPU','DPADISK','DPALOGICALDRIVE','DPANETADAPTER',
                       'DPATCPIP','DPAMEDIAADAPTER','DPADISPLAY','DPASWSUITE',
                       'DPANETDEVICE','DPANETPRINTER')
ORDER BY O.OBJECTNAME;
