spring:
  application:
    name: discovery-interface
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: ${MAXIMO_JDBC_URL}
    username: ${MAXIMO_JDBC_USERNAME}
    password: ${MAXIMO_JDBC_PASSWORD}
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0

device42:
  doql:
    rest:
      base-url: ${DEVICE42_REST_BASE_URL}
      username: ${DEVICE42_REST_USERNAME}
      password: ${DEVICE42_REST_PASSWORD}
      truststore: ${DEVICE42_TRUSTSTORE}
      truststore-password: ${DEVICE42_TRUSTSTORE_PASSWORD}
      connect-timeout: 10s
      response-timeout: 120s
    jdbc:
      driver-class-name: com.device42.jdbc.D42Driver
      url: ${DEVICE42_JDBC_URL}
      username: ${DEVICE42_JDBC_USERNAME}
      password: ${DEVICE42_JDBC_PASSWORD}
