-- 수동 실행용 Db2 SQL PL. 배치에서 자동 실행하지 않는다.
-- db2 CLP 사용 시 문장 구분자는 @로 지정한다.
-- 등록 대상: COMPUTERSYSTEM_BIOSRELEASEDATE(ALN), 두 Computer ACTCI 분류.
-- 기존 정의가 충돌하면 중단한다. 한 compound statement 안에서 원자적으로 등록한다.
BEGIN ATOMIC
    DECLARE attribute_id BIGINT;
    DECLARE template_id BIGINT;
    DECLARE display_order INTEGER;
    DECLARE class_count INTEGER;

    SELECT COUNT(*) INTO class_count
    FROM MAXIMO.CLASSSTRUCTURE s
    JOIN MAXIMO.CLASSUSEWITH u ON u.CLASSSTRUCTUREID=s.CLASSSTRUCTUREID
    WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
      AND u.OBJECTNAME='ACTCI';

    IF class_count <> 2 OR
       (SELECT COUNT(DISTINCT s.CLASSIFICATIONID)
        FROM MAXIMO.CLASSSTRUCTURE s
        JOIN MAXIMO.CLASSUSEWITH u ON u.CLASSSTRUCTUREID=s.CLASSSTRUCTUREID
        WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
          AND u.OBJECTNAME='ACTCI') <> 2 THEN
        SIGNAL SQLSTATE '75001' SET MESSAGE_TEXT='Expected one ACTCI classification per Computer type';
    END IF;

    IF EXISTS (
        SELECT 1 FROM MAXIMO.ASSETATTRIBUTE
        WHERE ASSETATTRID='COMPUTERSYSTEM_BIOSRELEASEDATE'
          AND (DATATYPE<>'ALN' OR ORGID IS NOT NULL OR SITEID IS NOT NULL)
    ) THEN
        SIGNAL SQLSTATE '75002' SET MESSAGE_TEXT='BIOSRELEASEDATE attribute conflicts with the required definition';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM MAXIMO.ASSETATTRIBUTE WHERE ASSETATTRID='COMPUTERSYSTEM_BIOSRELEASEDATE'
    ) THEN
        SET attribute_id = NEXT VALUE FOR MAXIMO.ASSETATTRIBUTESEQ;
        INSERT INTO MAXIMO.ASSETATTRIBUTE
            (ASSETATTRIBUTEID,ASSETATTRID,DESCRIPTION,DATATYPE,ROWSTAMP)
        VALUES (attribute_id,'COMPUTERSYSTEM_BIOSRELEASEDATE','BIOS release date (source text)',
                'ALN',NEXT VALUE FOR MAXIMO.MAXSEQ);
    END IF;

    SELECT ASSETATTRIBUTEID INTO attribute_id FROM MAXIMO.ASSETATTRIBUTE
    WHERE ASSETATTRID='COMPUTERSYSTEM_BIOSRELEASEDATE';

    FOR selected_class AS
        SELECT s.CLASSSTRUCTUREID
        FROM MAXIMO.CLASSSTRUCTURE s
        JOIN MAXIMO.CLASSUSEWITH u ON u.CLASSSTRUCTUREID=s.CLASSSTRUCTUREID
        WHERE s.CLASSIFICATIONID IN ('SYS.COMPUTERSYSTEM','SYS.VIRTUALCOMPUTERSYSTEM')
          AND u.OBJECTNAME='ACTCI'
    DO
        IF EXISTS (
            SELECT 1 FROM MAXIMO.CLASSSPEC c
            WHERE c.CLASSSTRUCTUREID=selected_class.CLASSSTRUCTUREID
              AND c.ASSETATTRID='COMPUTERSYSTEM_BIOSRELEASEDATE'
              AND (c.SECTION IS NOT NULL OR c.ASSETATTRIBUTEID IS NULL
                   OR c.ASSETATTRIBUTEID<>attribute_id OR c.MEASUREUNITID IS NOT NULL
                   OR c.DOMAINID IS NOT NULL)
        ) THEN
            SIGNAL SQLSTATE '75003' SET MESSAGE_TEXT='BIOSRELEASEDATE template conflicts with the required definition';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM MAXIMO.CLASSSPEC c
            WHERE c.CLASSSTRUCTUREID=selected_class.CLASSSTRUCTUREID
              AND c.ASSETATTRID='COMPUTERSYSTEM_BIOSRELEASEDATE'
        ) THEN
            SET template_id = NEXT VALUE FOR MAXIMO.CLASSSPECSEQ;
            INSERT INTO MAXIMO.CLASSSPEC
                (CLASSSPECID,CLASSSTRUCTUREID,ASSETATTRID,ASSETATTRIBUTEID,
                 APPLYDOWNHIER,CONTINUOUS,PLUSPISGLOBAL,ROWSTAMP)
            VALUES (template_id,selected_class.CLASSSTRUCTUREID,'COMPUTERSYSTEM_BIOSRELEASEDATE',
                    attribute_id,0,0,1,NEXT VALUE FOR MAXIMO.MAXSEQ);
        END IF;

        SELECT c.CLASSSPECID INTO template_id FROM MAXIMO.CLASSSPEC c
        WHERE c.CLASSSTRUCTUREID=selected_class.CLASSSTRUCTUREID
          AND c.ASSETATTRID='COMPUTERSYSTEM_BIOSRELEASEDATE' AND c.SECTION IS NULL;

        IF EXISTS (
            SELECT 1 FROM MAXIMO.CLASSSPECUSEWITH u
            WHERE u.CLASSSPECID=template_id AND u.OBJECTNAME='ACTCI'
              AND (u.CLASSSTRUCTUREID<>selected_class.CLASSSTRUCTUREID
                   OR u.ASSETATTRID<>'COMPUTERSYSTEM_BIOSRELEASEDATE'
                   OR u.SECTION IS NOT NULL OR u.USEINSPEC<>1 OR u.MANDATORY<>0)
        ) THEN
            SIGNAL SQLSTATE '75004' SET MESSAGE_TEXT='BIOSRELEASEDATE ACTCI usage conflicts with the required definition';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM MAXIMO.CLASSSPECUSEWITH u
            WHERE u.CLASSSPECID=template_id AND u.OBJECTNAME='ACTCI'
        ) THEN
            SELECT COALESCE(MAX(u.SEQUENCE),0)+1 INTO display_order
            FROM MAXIMO.CLASSSPECUSEWITH u
            WHERE u.CLASSSTRUCTUREID=selected_class.CLASSSTRUCTUREID AND u.OBJECTNAME='ACTCI';

            IF display_order>32767 THEN
                SIGNAL SQLSTATE '75005' SET MESSAGE_TEXT='ACTCISPEC display order exceeds SMALLINT';
            END IF;

            INSERT INTO MAXIMO.CLASSSPECUSEWITH
                (CLASSSPECUSEWITHID,CLASSSPECID,CLASSSTRUCTUREID,ASSETATTRID,
                 MANDATORY,SEQUENCE,USEINDESC,USEINSPEC,OBJECTNAME,OBJECTVALUE,ROWSTAMP)
            VALUES (NEXT VALUE FOR MAXIMO.CLASSSPECUSEWITHSEQ,template_id,
                    selected_class.CLASSSTRUCTUREID,'COMPUTERSYSTEM_BIOSRELEASEDATE',
                    0,display_order,0,1,'ACTCI','ACTCI',NEXT VALUE FOR MAXIMO.MAXSEQ);
        END IF;
    END FOR;
END
@
