CREATE SCHEMA MAXIMO;
CREATE SEQUENCE MAXIMO.ACTCISEQ START WITH 1001 INCREMENT BY 1000;
CREATE SEQUENCE MAXIMO.ACTCISPECSEQ START WITH 2001 INCREMENT BY 1000;
CREATE TABLE MAXIMO.CLASSSTRUCTURE (CLASSSTRUCTUREID VARCHAR(25) PRIMARY KEY, CLASSIFICATIONID VARCHAR(100));
CREATE TABLE MAXIMO.CLASSUSEWITH (CLASSSTRUCTUREID VARCHAR(25), OBJECTNAME VARCHAR(30));
CREATE TABLE MAXIMO.ASSETATTRIBUTE (ASSETATTRIBUTEID BIGINT PRIMARY KEY, ASSETATTRID VARCHAR(300), DATATYPE VARCHAR(8));
CREATE TABLE MAXIMO.CLASSSPEC (
    CLASSSTRUCTUREID VARCHAR(25), CLASSSPECID BIGINT PRIMARY KEY, ASSETATTRID VARCHAR(300),
    ASSETATTRIBUTEID BIGINT, SECTION VARCHAR(10), MEASUREUNITID VARCHAR(16),
    LINKEDTOATTRIBUTE VARCHAR(300), LINKEDTOSECTION VARCHAR(10)
);
CREATE TABLE MAXIMO.CLASSSPECUSEWITH (
    CLASSSPECID BIGINT, OBJECTNAME VARCHAR(30), SEQUENCE INTEGER, MANDATORY INTEGER, USEINSPEC INTEGER,
    CLASSSTRUCTUREID VARCHAR(25), ASSETATTRID VARCHAR(300), SECTION VARCHAR(10)
);
CREATE TABLE MAXIMO.MEASUREUNIT (MEASUREUNITID VARCHAR(16));
CREATE TABLE MAXIMO.ACTCI (
    ACTCIID BIGINT PRIMARY KEY, ACTCINUM VARCHAR(150) NOT NULL UNIQUE,
    ACTCINAME VARCHAR(192), CLASSSTRUCTUREID VARCHAR(25), DESCRIPTION VARCHAR(1024),
    LASTSCANDT TIMESTAMP NOT NULL, CHANGEBY VARCHAR(100), CHANGEDATE TIMESTAMP,
    LANGCODE VARCHAR(4) NOT NULL, HASLD INTEGER NOT NULL
);
CREATE TABLE MAXIMO.ACTCISPEC (
    ACTCISPECID BIGINT PRIMARY KEY, ACTCINUM VARCHAR(150) NOT NULL,
    ASSETATTRID VARCHAR(300) NOT NULL, CLASSSTRUCTUREID VARCHAR(25) NOT NULL,
    CLASSSPECID BIGINT, SECTION VARCHAR(10), REFOBJECTID BIGINT, REFOBJECTNAME VARCHAR(30),
    DISPLAYSEQUENCE SMALLINT NOT NULL, MANDATORY INTEGER NOT NULL,
    MEASUREUNITID VARCHAR(16), LINKEDTOATTRIBUTE VARCHAR(300), LINKEDTOSECTION VARCHAR(10),
    ALNVALUE VARCHAR(254), NUMVALUE DECIMAL(30,10), TABLEVALUE VARCHAR(254),
    CHANGEBY VARCHAR(100) NOT NULL, CHANGEDATE TIMESTAMP NOT NULL,
    UNIQUE (ASSETATTRID,ACTCINUM,SECTION)
);
